import { atom, useAtomValue } from 'jotai';

// Fallback dictionary for all React-specific web interface strings
export const reactDefaultPhrases: Record<string, string> = {
    "web.login.welcome_back": "Welcome back",
    "web.login.enter_credentials": "Enter your credentials to access the %{servername} dashboard",
    "web.login.sign_in_cfx": "Sign in with Cfx.re",
    "web.login.or_continue": "OR CONTINUE WITH EMAIL",
    "web.login.username_placeholder": "name@example.com",
    "web.login.password_placeholder": "Password",
    "web.login.anmelden": "Sign In",
    "web.login.remember_creds": "Remember credentials",
    "web.login.no_admins_setup": "No admins set up.\nRedirecting...",
    "web.login.msg_logged_out": "Logged Out.",
    "web.login.msg_session_expired": "Session Expired.",
    "web.login.msg_updated": "vibeSM updated!\nPlease login again.",
    "web.login.msg_master_already_configured": "Master account already configured.",
    "web.login.msg_shutdown": "The vibeSM server shut down.\nPlease start it again to be able to login.",
    "web.login.verify_setup": "Verify & Setup",
    
    // Auth Errors
    "web.auth_error.invalid_session_title": "Invalid Browser Session.",
    "web.auth_error.invalid_session_desc_1": "You may have restarted vibeSM right before entering this page.",
    "web.auth_error.invalid_session_desc_2": "Please return and try again.",
    "web.auth_error.clock_desync_title": "Please Update/Synchronize your VPS clock.",
    "web.auth_error.clock_desync_desc": "Failed to login because this host's time is wrong. Please make sure to synchronize it with the internet.",
    "web.auth_error.timeout_title": "Connection to FiveM servers timed out.",
    "web.auth_error.timeout_desc": "Please try again or login using your existing username and backup password.",
    "web.auth_error.login_aborted_title": "Login Aborted",
    "web.auth_error.login_aborted_desc_1": "The Cfx.re login process was aborted.",
    "web.auth_error.login_aborted_desc_2": "Return to the login page to try again.",
    "web.auth_error.login_logout_desc_1": "The Cfx.re login process was aborted because you logged out of the Cfx.re account.",
    "web.auth_error.login_logout_desc_2": "Return to the login page to try again.",
    "web.auth_error.master_set_title": "Master Account Already Set",
    "web.auth_error.master_set_desc": "Please go back to the login page to continue.",
    "web.auth_error.not_admin_title": "The Cfx.re account '%{name}' is not an admin.",
    "web.auth_error.not_admin_desc_1": "The account above with identifier ",
    "web.auth_error.not_admin_desc_2": " is not assigned to any account registered on vibeSM.",
    "web.auth_error.not_admin_desc_3": "You can also try to login using your username and backup password.",
    "web.auth_error.unknown_error_title": "Unknown Error:",
    "web.auth_error.try_again": "Try Again",
    "web.auth_error.network_error": "Network Error",
    "web.auth_error.restart_desc": "If you closed vibeSM, please restart it and try again.",
    "web.auth_error.unknown_error": "Unknown Error",
    
    // Auth PIN and Register Flows
    "web.auth.pin.autofilled": "Auto-filled ✔",
    "web.auth.pin.no_cfx_linked": "No Cfx.re account linked",
    "web.auth.pin.instructions": "Type in the PIN from the terminal.",
    "web.auth.pin.link_btn": "Link Account",
    "web.auth.register.err_discord_id": "The Discord ID needs to be the numeric \"User ID\" instead of the username.\n You can also leave it blank.",
    "web.auth.register.err_agree_terms": "You MUST agree to the terms.",
    "web.auth.register.err_password_length": "The password must be between %{min} and %{max} characters long.",
    "web.auth.register.err_passwords_dont_match": "The passwords do not match.",
    "web.auth.register.cfx_account": "Cfx.re account",
    "web.auth.register.discord_id": "Discord ID",
    "web.auth.register.optional": "(optional)",
    "web.auth.register.backup_password": "Backup Password",
    "web.auth.register.confirm_password": "Confirm Password",
    "web.auth.register.terms_prefix": "I have read and agree to the ",
    "web.auth.register.creator_pla": "Creator PLA",
    "web.auth.register.terms_and": " as well as the ",
    "web.auth.register.license_link": "vibeSM License",
    "web.auth.register.register_btn": "Register",
    "web.auth.register.authenticating": "Authenticating...",
    "web.auth.login.logging_in": "Logging in...",
    
    // NotFound Page
    "web.notfound.title": "Not Found",
    "web.notfound.header": "404 | Not Found",
    "web.notfound.desc": "The page %{path} does not seem to be correct.",
    "web.notfound.return": "Return to Dashboard?",
    
    // Unauthorized Page
    "web.unauthorized.permission": "permission",
    "web.unauthorized.master_required": "You need to be the Master account to view the %{page} page.",
    "web.unauthorized.perms_required_prefix": "You don't have the required ",
    "web.unauthorized.perms_required_suffix": " to view the %{page} page.",
    "web.unauthorized.contact_owner": "Please contact your server owner if you believe this is an error.",
    "web.unauthorized.access_denied": "Access Denied",
    "web.unauthorized.return": "Return to Dashboard",
    
    // AddLegacyBan Page
    "web.ban.err_reason_length": "The reason must be at least 3 characters long.",
    "web.ban.err_no_identifiers": "You must enter at least one identifier.",
    "web.ban.err_invalid_identifiers": "You must enter at least one valid identifier.",
    "web.ban.banning_toast": "Banning identifiers...",
    "web.ban.banned_toast": "Identifiers banned.",
    "web.ban.title": "Ban Identifiers",
    "web.ban.desc_main_1": "Here you can ban specific player identifiers (like ",
    "web.ban.desc_main_2": " and ",
    "web.ban.desc_main_3": ") without having to search for a registered player.",
    "web.ban.desc_legacy_1": "Bans without a single ",
    "web.ban.desc_legacy_2": " identifier are considered ",
    "web.ban.desc_legacy_3": " and should be avoided if possible.",
    "web.ban.err_permission_1": "You need the ",
    "web.ban.err_permission_2": " permission to use this feature.",
    "web.ban.identifiers_label": "Identifiers",
    "web.ban.identifiers_placeholder": "discord:xxxx, fivem:xxxx, license:xxxx, steam:xxxx, etc...",
    "web.ban.clear_btn": "Clear",
    "web.ban.banning_btn": "Banning...",
    "web.ban.apply_btn": "Apply Ban",
    
    // Multi-Hosting Page
    "web.multi_hosting.loading": "Loading servers...",
    "web.multi_hosting.save_success": "Server configuration saved successfully.",
    "web.multi_hosting.err_fields": "Failed to save server configuration. Please check the fields.",
    "web.multi_hosting.delete_confirm": "Are you sure you want to delete this server configuration?",
    "web.multi_hosting.delete_success": "Server configuration deleted successfully.",
    "web.multi_hosting.start_success": "Server start command sent successfully.",
    "web.multi_hosting.stop_success": "Server stop command sent successfully.",
    "web.multi_hosting.title": "Multi-Hosting",
    "web.multi_hosting.description": "Deploy, configure, start, stop, and manage multiple separate FXServer instances from a single panel.",
    "web.multi_hosting.add_server": "Add existing Server",
    "web.multi_hosting.create_server": "Create a new Server",
    "web.multi_hosting.create_and_deploy": "Create a new Server & Deploy",
    "web.multi_hosting.edit_server": "Edit Server Configuration",
    "web.multi_hosting.new_server": "Add New Server",
    "web.multi_hosting.base_settings": "Base Settings",
    "web.multi_hosting.discord_bot": "Discord Bot",
    "web.multi_hosting.bans": "Bans",
    "web.multi_hosting.whitelist": "Whitelist",
    "web.multi_hosting.server_name": "Server Name",
    "web.multi_hosting.port": "Port",
    "web.multi_hosting.port_info": "Ensure this port is open on your firewall for both TCP and UDP.",
    "web.multi_hosting.data_path": "Server Data Path",
    "web.multi_hosting.base_dir_path": "Base Directory Path (where server will be created/deployed)",
    "web.multi_hosting.cfg_path": "CFG File Path",
    "web.multi_hosting.join_link": "Join Link:",
    "web.multi_hosting.loading_configs": "Loading configs...",
    "web.multi_hosting.err_loading_configs": "Error loading configs: %{error}",
    "web.multi_hosting.saving_server_config": "Saving server configuration...",
    "web.multi_hosting.saving_settings": "Saving %{card} settings...",
    "web.multi_hosting.err_saving_settings": "Error saving %{card} settings:",
    "web.multi_hosting.cancel": "Cancel",
    "web.multi_hosting.saving": "Saving...",
    "web.multi_hosting.save": "Save",
    "web.multi_hosting.no_servers": "No Servers Configured",
    "web.multi_hosting.no_servers_desc": "Deploy or link your first FXServer configuration to get started.",
    "web.multi_hosting.online": "Online",
    "web.multi_hosting.starting": "Starting",
    "web.multi_hosting.offline": "Offline",
    "web.multi_hosting.running_port": "Port",
    "web.multi_hosting.stop": "Stop",
    "web.multi_hosting.start": "Start",
    "web.multi_hosting.edit": "Edit",
    
    // System-Log Page
    "web.system_log.end_of_log": "[END OF LOG - REFRESH THE PAGE TO LOAD MORE]",
    "web.system_log.console_title": "Console Log",
    "web.system_log.console_desc": "Output of vibeSM to its parent terminal, including usually hidden debug messages.",
    "web.system_log.action_title": "Action Log",
    "web.system_log.action_desc": "Log of all actions taken by vibeSM or any admin.",
    "web.system_log.loading": "Loading...",
    "web.system_log.err_fetching": "Error fetching %{title}:",
    
    // Dashboard Page
    "web.dashboard.err_unknown_state": "Unknown Config State: %{state}",
    "web.dashboard.stats.uptime": "Uptime",
    "web.dashboard.stats.median": "Median",
    "web.dashboard.stats.fxserver": "FXServer",
    "web.dashboard.stats.nodejs": "Node.js",
    "web.dashboard.stats.title": "Server Stats",
    "web.dashboard.stats.minutes_ago": "(minutes ago)",
    "web.dashboard.stats.live": "(live)",
    "web.dashboard.player_drop.total": "Total:",
    "web.dashboard.player_drop.no_disconnects": "No players have disconnected from the server in the last 6 hours.",
    "web.dashboard.player_drop.title": "Player Drop Cause (last 6h)",
    "web.dashboard.perf.tick_duration": "Tick duration:",
    "web.dashboard.perf.time_spent": "Time spent:",
    "web.dashboard.perf.tick_count": "Tick count:",
    "web.dashboard.perf.percent_total": "percent of total time",
    "web.dashboard.perf.good": "good",
    "web.dashboard.perf.bad": "bad",
    "web.dashboard.perf.last_minute": "(last minute)",
    "web.dashboard.perf.no_data": "Data not yet available. The thread performance chart will appear soon after the server is online.",
    "web.dashboard.perf.title": "%{thread} Performance",
    "web.dashboard.perf.filter_placeholder": "Filter by admin",
    "web.dashboard.full_perf.render_error": "Render Error: %{error}",
    "web.dashboard.full_perf.retry": "Retry",
    "web.dashboard.full_perf.err_bad_request": "Chart data loading failed: bad request.",
    "web.dashboard.full_perf.err_invalid_thread": "Chart data loading failed: invalid thread name.",
    "web.dashboard.full_perf.err_data_unavailable": "Chart data loading failed: data not yet available.",
    "web.dashboard.full_perf.not_enough_data_1": "There is not enough data to display the chart just yet.",
    "web.dashboard.full_perf.not_enough_data_2": "The chart requires at least 30 minutes of server runtime data to be available.",
    "web.dashboard.full_perf.title": "Server Performance",
    
    // Sidebar / Navigation
    "web.sidebar.dashboard": "Dashboard",
    "web.sidebar.players": "Players",
    "web.sidebar.history": "History",
    "web.sidebar.insights": "Player Drops",
    "web.sidebar.whitelist": "Whitelist",
    "web.sidebar.admins": "Admins",
    "web.sidebar.settings": "Settings",
    "web.sidebar.system": "System",
    "web.sidebar.master_actions": "Master Actions",
    "web.sidebar.diagnostics": "Diagnostics",
    "web.sidebar.console_log": "Console Log",
    "web.sidebar.action_log": "Action Log",
    "web.sidebar.console": "Live Console",
    "web.sidebar.resources": "Resources",
    "web.sidebar.server_log": "Server Log",
    "web.sidebar.cfg_editor": "CFG Editor",
    "web.sidebar.advanced": "Advanced",

    // Header Components
    "web.header.server": "Server",
    "web.header.menu": "Menu",
    "web.header.players": "Players",
    "web.header.light_mode": "Light Mode",
    "web.header.dark_mode": "Dark Mode",
    "web.header.account": "Your Account",
    "web.header.support": "Support",
    "web.header.logout": "Logout",
    
    // Settings Tabs
    "web.settings.tab_general": "General",
    "web.settings.tab_language": "Language",
    "web.settings.tab_fxserver": "FXServer",
    "web.settings.tab_theme": "Theme",
    "web.settings.tab_bans": "Bans",
    "web.settings.tab_whitelist": "Whitelist",
    "web.settings.tab_discord": "Discord",
    "web.settings.tab_game": "Game",
    "web.settings.tab_menu": "Menu",
    "web.settings.tab_notifications": "Notifications",
    "web.settings.enabled": "Enabled",
    "web.settings.disabled": "Disabled",
    
    // Theme Card
    "web.theme.active_theme": "Active Theme",
    "web.theme.creator": "Theme Creator",
    "web.theme.create_dynamic": "Create Dynamic Theme",
    "web.theme.variable_to_edit": "Edit Color Variable",
    
    // Language Card
    "web.language.active_system": "Active System Language",
    "web.language.custom_editor": "Custom Translations Editor",
    "web.language.save_translations": "Save Translations",
    "web.language.apply_language": "Apply Language",

    // Two-Factor Auth
    "web.2fa.title": "Two-Factor Authentication",
    "web.2fa.setup_required": "Two-Factor Authentication is required by global settings.",
    "web.2fa.enter_code": "Please enter your 6-digit verification code.",
    "web.2fa.placeholder": "6-digit verification code",
    "web.2fa.cancel": "Cancel",
    "web.2fa.verify_enable": "Verify & Enable",
    "web.2fa.verify_code": "Verify Code",
    "web.2fa.back": "Back",
    "web.2fa.active": "Active",
    "web.2fa.enabled_msg": "Two-factor authentication is enabled.",
    "web.2fa.secured_msg": "Your account is secured with an Authenticator app. You will be prompted to enter a verification code when logging in with your password.",
    "web.2fa.verification_code": "Verification Code",
    "web.2fa.disable_placeholder": "Enter 6-digit code to disable",
    "web.2fa.disabling": "Disabling...",
    "web.2fa.disable_btn": "Disable 2FA",
    "web.2fa.intro_msg": "Two-factor authentication adds an extra layer of security to your account by requiring a verification code from an Authenticator app (e.g. Google Authenticator, Authy, Microsoft Authenticator) when logging in.",
    "web.2fa.generating": "Generating Setup...",
    "web.2fa.setup_btn": "Set Up Authenticator",
    "web.2fa.scan_msg": "Scan the QR code with your Authenticator app, or enter the manual key below. Then, enter the 6-digit code shown in the app to complete setup.",
    "web.2fa.key": "Key: %{key}",
    "web.2fa.verifying": "Verifying...",
    "web.2fa.settings_title": "Two-Factor Authentication Requirement",
    "web.2fa.settings_switch": "Require Two-Factor Authentication (2FA) for Web Panel access",
    "web.2fa.settings_desc": "When enabled, all administrators using password login will be forced to scan a QR code and configure 2FA upon login before they can access the web panel.",
    "web.2fa.settings_only_master": " Only a Master Account can change this setting.",

    // Settings: Bans Card
    "web.settings.bans.checking": "Ban Checking",
    "web.settings.bans.checking_desc": "Enable checking for ban status on player join. Note: vibeSM bans will not work if this option is disabled.",
    "web.settings.bans.templates": "Ban Templates",
    "web.settings.bans.templates_edit": "Edit Ban Templates",
    "web.settings.bans.templates_desc": "Configure ban reasons and durations that will appear as dropdown options when banning a player. This is useful for common reasons that happen frequently, like violation of your server rules.",
    "web.settings.bans.rejection": "Ban Rejection Message",
    "web.settings.bans.rejection_placeholder": "You can join http://discord.gg/example to appeal this ban.",
    "web.settings.bans.rejection_desc": "Optional message to display to a player on the rejection message that shows when they try to connect while being banned. If you have a ban appeal process, you can use this field to inform the players.",
    "web.settings.bans.validation_title": "The Ban Rejection Message is too big.",
    "web.settings.bans.validation_msg": "The message must be 512 characters or less.",
    "web.settings.bans.hwid": "Required Ban HWID Matches",
    "web.settings.bans.hwid_desc": "This option configures how many HWID tokens must match between a player and an existing ban for the player join to be blocked, or can disable HWID Bans entirely. Since Hardware ID Tokens are not guaranteed to be unique, there is the possibility of tokens from two players matching without them being related to each other. Note: Most players have 3 to 6 HWID tokens.",
    "web.settings.bans.hwid_opt1": "1 - recommended",
    "web.settings.bans.hwid_opt2": "2 - lax",
    "web.settings.bans.hwid_opt3": "3 - very lax",
    "web.settings.bans.hwid_opt4": "4 - virtually disabled",
    "web.settings.bans.hwid_opt0": "Disable HWID Bans",

    // Settings: Queue Card
    "web.settings.queue.enabled": "Connection Queue",
    "web.settings.queue.enabled_desc": "Enable connection queue when server is full or when there is a queue.",
    "web.settings.queue.priority_roles": "Priority Discord Roles",
    "web.settings.queue.priority_roles_desc": "Discord Role IDs that receive priority inside the connection queue (separated by comma).",
    "web.settings.queue.team_roles": "Team/Staff Discord Roles",
    "web.settings.queue.team_roles_desc": "Discord Role IDs for staff members who bypass the connection queue entirely (separated by comma).",
    "web.settings.queue.max_slots": "Custom Max Slots",
    "web.settings.queue.max_slots_desc": "Override maximum slots for the queue system (0 to auto-detect from FXServer maxClients).",
    "web.settings.queue.priority_label": "Priority Role Label",
    "web.settings.queue.priority_label_desc": "Label displayed in the queue text for priority role players.",
    "web.settings.queue.standard_label": "Standard Role Label",
    "web.settings.queue.standard_label_desc": "Label displayed in the queue text for standard players.",
    "web.settings.queue.msg_template": "Queue Console Message Template",
    "web.settings.queue.msg_template_desc": "Custom console message layout displayed in the connection fallback dialog. Supports placeholders: {{position}}, {{queueLength}}, {{queueType}}, {{activePlayers}}, {{maxSlots}}, {{elapsedTime}}.",
    "web.settings.queue.card_template": "Adaptive Card Template JSON",
    "web.settings.queue.card_template_desc": "Custom AdaptiveCard JSON to show players waiting in the queue. Supports placeholders: {{playerName}}, {{avatarURL}}, {{position}}, {{queueLength}}, {{elapsedTime}}, {{queueType}}.",
    "web.settings.queue.val_priority_roles_title": "Invalid Priority Discord Role ID(s).",
    "web.settings.queue.val_team_roles_title": "Invalid Team Discord Role ID(s).",
    "web.settings.queue.val_roles_msg": "The following role ID(s) are invalid: \n%{roles}",
    "web.settings.queue.val_json_title": "Invalid Adaptive Card JSON",
    "web.settings.queue.val_json_msg": "Please check that the JSON is valid: %{error}",

    // Settings: General Card
    "web.settings.general.server_name": "Server Name",
    "web.settings.general.server_name_required": "The Server Name is required.",
    "web.settings.general.server_name_too_big": "The Server Name is too big.",
    "web.settings.general.server_name_desc1": "A ",
    "web.settings.general.server_name_desc2": "short",
    "web.settings.general.server_name_desc3": " server name to be used in the vibeSM interface and Server/Discord messages.",
    "web.settings.general.server_name_desc4": "The name must be between 1 and 18 characters.",
    "web.settings.general.language": "Language",
    "web.settings.general.language_desc1": "The language to use on Chat/Discord messages.",
    "web.settings.general.language_desc2": "You can customize the phrases/words by using the ",
    "web.settings.general.language_desc3": " option.",
    "web.settings.general.language_desc4": "For more information, please read the ",
    "web.settings.general.language_desc5": "documentation",

    // Settings: Whitelist Card
    "web.settings.whitelist.label": "Whitelist Mode",
    "web.settings.whitelist.mode_disabled": "Disabled",
    "web.settings.whitelist.mode_disabled_desc": "No whitelist status will be checked by vibeSM.",
    "web.settings.whitelist.mode_admin": "Admin-only (maintenance mode)",
    "web.settings.whitelist.mode_admin_desc1": "Will only allow server join if your ",
    "web.settings.whitelist.mode_admin_desc2": " identifiers are attached to a vibeSM administrator. Also known as maintenance mode.",
    "web.settings.whitelist.mode_discord_member": "Discord Server Member",
    "web.settings.whitelist.mode_discord_member_desc1": "Checks if the player joining has a ",
    "web.settings.whitelist.mode_discord_member_desc2": " identifier and is present in the Discord server configured in the Discord Tab.",
    "web.settings.whitelist.mode_discord_roles": "Discord Server Roles",
    "web.settings.whitelist.mode_discord_roles_desc1": "Checks if the player joining has a ",
    "web.settings.whitelist.mode_discord_roles_desc2": " identifier and is present in the Discord server configured in the Discord Tab and has at least one of the roles specified below.",
    "web.settings.whitelist.mode_approved": "Approved License",
    "web.settings.whitelist.mode_approved_desc1": "The player ",
    "web.settings.whitelist.mode_approved_desc2": " identifier must be whitelisted by a vibeSM administrator. This can be done through the ",
    "web.settings.whitelist.mode_approved_desc3": "Whitelist page",
    "web.settings.whitelist.mode_approved_desc4": ", or the ",
    "web.settings.whitelist.mode_approved_desc5": " Discord bot slash command.",
    "web.settings.whitelist.mode_external": "External Allowlist Resource",
    "web.settings.whitelist.mode_external_desc": "Select this option if you are using an external allowlist system to manage which players can join the server.",
    "web.settings.whitelist.note": "Note:",
    "web.settings.whitelist.note_desc": " Players will see \"Allowlist Enabled\" icon in the server list.",
    "web.settings.whitelist.rejection_label": "Whitelist Rejection Message",
    "web.settings.whitelist.rejection_placeholder": "Please join http://discord.gg/example and request to be whitelisted.",
    "web.settings.whitelist.rejection_desc1": "Optional message to display to a player on the rejection message that shows when they try to connect while not being whitelisted.",
    "web.settings.whitelist.rejection_desc2": "If you have a Discord whitelisting process, include here a invite link.",
    "web.settings.whitelist.allowlist_instructions_label": "Allowlist Instructions",
    "web.settings.whitelist.allowlist_instructions_placeholder": "Enter instructions for how to get allowlisted...",
    "web.settings.whitelist.allowlist_instructions_desc1": "Instructions on how to get allowlisted. This activates the ",
    "web.settings.whitelist.allowlist_instructions_desc2": " convar when filled.",
    "web.settings.whitelist.discord_roles_label": "Whitelisted Discord Roles",
    "web.settings.whitelist.discord_roles_placeholder": "000000000000000000, 000000000000000000",
    "web.settings.whitelist.discord_roles_desc1": "The ID of the Discord roles that are whitelisted to join the server.",
    "web.settings.whitelist.discord_roles_desc2": "This field supports multiple roles, separated by comma.",
    "web.settings.whitelist.discord_roles_desc3": "Requires the whitelist mode to be set to \"Discord Server Roles\".",
    "web.settings.whitelist.val_rejection_title": "The Whitelist Rejection Message is too big.",
    "web.settings.whitelist.val_rejection_msg": "The message must be 512 characters or less.",
    "web.settings.whitelist.val_bot_required_title": "Discord Bot is required.",
    "web.settings.whitelist.val_bot_required_msg": "You need to enable the Discord Bot in the Discord tab to use Discord-based whitelist modes.",
    "web.settings.whitelist.val_roles_required_title": "Discord Roles are required.",
    "web.settings.whitelist.val_roles_required_msg": "You need to specify at least one Discord Role ID to use the \"Discord Server Roles\" whitelist mode.",
    "web.settings.whitelist.val_invalid_roles_title": "Invalid Discord Role ID(s).",
    "web.settings.whitelist.val_invalid_roles_msg": "The following Discord Role ID(s) are invalid: \n%{roles}",

    // Settings: Discord Card
    "web.settings.discord.bot_label": "Discord Bot",
    "web.settings.discord.bot_desc": "Enable Discord Integration.",
    "web.settings.discord.token_label": "Token",
    "web.settings.discord.token_placeholder": "xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "web.settings.discord.token_desc1": "To get a token and the bot to join your server, follow these two guides:",
    "web.settings.discord.token_desc2": "Setting up a bot application",
    "web.settings.discord.token_desc3": "Adding your bot to servers",
    "web.settings.discord.token_desc4": "Do not reuse the same token for another bot.",
    "web.settings.discord.token_desc5": "The bot requires the",
    "web.settings.discord.token_desc6": "Server Members",
    "web.settings.discord.token_desc7": "intent, which can be set at the",
    "web.settings.discord.token_desc8": "Discord Developer Portal",
    "web.settings.discord.guild_label": "Guild/Server ID",
    "web.settings.discord.guild_placeholder": "000000000000000000",
    "web.settings.discord.guild_desc1": "The ID of the Discord Server (also known as Discord Guild).",
    "web.settings.discord.guild_desc2": "To get the Server ID, go to Discord's settings and",
    "web.settings.discord.guild_desc3": " enable developer mode",
    "web.settings.discord.guild_desc4": ", then right-click on the guild icon select \"Copy ID\".",
    "web.settings.discord.warnings_channel_label": "Warnings Channel ID",
    "web.settings.discord.warnings_channel_placeholder": "000000000000000000",
    "web.settings.discord.warnings_channel_desc1": "The ID of the channel to send Announcements (eg server restarts).",
    "web.settings.discord.warnings_channel_desc2": "You can leave it blank to disable this feature.",
    "web.settings.discord.warnings_channel_desc3": "To get the channel ID, go to Discord's settings and",
    "web.settings.discord.warnings_channel_desc4": " enable developer mode",
    "web.settings.discord.warnings_channel_desc5": ", then right-click on the channel name and select \"Copy ID\".",
    "web.settings.discord.allow_dangerous_perms_label": "Allow Dangerous Permissions",
    "web.settings.discord.allow_dangerous_perms_desc1": "Allow the Discord Bot to start even if it has potentially dangerous administrative permissions.",
    "web.settings.discord.allow_dangerous_perms_desc2": "Warning: Keeping this disabled is recommended for security.",
    "web.settings.discord.allow_dangerous_perms_allowed": "Allowed",
    "web.settings.discord.allow_dangerous_perms_forbidden": "Forbidden",
    "web.settings.discord.activity_type_label": "Activity Type",
    "web.settings.discord.activity_type_placeholder": "Select type...",
    "web.settings.discord.activity_type_desc": "The type of activity displayed on the bot's Discord presence.",
    "web.settings.discord.activity_type_playing": "Playing",
    "web.settings.discord.activity_type_streaming": "Streaming",
    "web.settings.discord.activity_type_listening": "Listening",
    "web.settings.discord.activity_type_watching": "Watching",
    "web.settings.discord.activity_type_competing": "Competing",
    "web.settings.discord.activity_desc_label": "Activity Description",
    "web.settings.discord.activity_desc_placeholder": "[{{players}}/{{maxClients}}] on {{serverName}}",
    "web.settings.discord.activity_desc_desc1": "The activity message status text. Supports the following placeholders:",
    "web.settings.discord.activity_desc_desc2": "Online player count",
    "web.settings.discord.activity_desc_desc3": "Maximum player capacity",
    "web.settings.discord.activity_desc_desc4": "The server name",
    "web.settings.discord.activity_desc_desc5": "Leave empty to use the default:",
    "web.settings.discord.activity_desc_starting_label": "Activity Description (Server Starting)",
    "web.settings.discord.activity_desc_starting_placeholder": "Server starting...",
    "web.settings.discord.activity_desc_starting_desc1": "The activity message status text shown while the FXServer is booting/starting.",
    "web.settings.discord.activity_desc_starting_desc2": "Leave empty to use the default:",
    "web.settings.discord.status_embed_json_label": "Status Embed JSON",
    "web.settings.discord.status_config_json_label": "Status Config JSON",
    "web.settings.discord.embed_desc1": "The server status embed is customizable by editing the JSON above.",
    "web.settings.discord.embed_desc2": "Note:",
    "web.settings.discord.embed_desc3": " Use the command ",
    "web.settings.discord.embed_desc4": " on a channel that the bot has the \"Send Message\" permission to setup the embed.",
    "web.settings.discord.discard_changes": "Discard Changes",
    "web.settings.discord.reset_default": "Reset to Default",
    "web.settings.discord.val_token_required": "You must provide a Discord Bot Token to enable the bot.",
    "web.settings.discord.val_guild_required": "You must provide a Server ID to enable the bot.",
    "web.settings.discord.val_jsons_required": "You must provide both the Embed JSON and Config JSON to enable the bot.",

    // Settings: FXServer Card
    "web.settings.fxserver.data_folder_label": "Server Data Folder",
    "web.settings.fxserver.data_folder_required": "The Server Data Folder is required.",
    "web.settings.fxserver.data_folder_setup": "If you want to return to the Setup page, click on the \"Reset\" button instead.",
    "web.settings.fxserver.cfg_path_required": "The CFG File Path is required.",
    "web.settings.fxserver.cfg_path_suggested": "The value should probably be `server.cfg`.",
    "web.settings.fxserver.onesync_err_title": "You cannot set OneSync in Startup Arguments.",
    "web.settings.fxserver.onesync_err_msg": "Please use the selectbox below it.",
    "web.settings.fxserver.reset_data_title": "Reset Server Data Path",
    "web.settings.fxserver.reset_data_msg1": "Are you sure you want to reset the server data path?",
    "web.settings.fxserver.reset_data_msg2": "This will not delete any resource files or database",
    "web.settings.fxserver.reset_data_msg3": ", but just reset the vibeSM configuration, allowing you to go back to the Setup page.",
    "web.settings.fxserver.reset_data_msg4": "If you want, you can set the path back to the current value later.",
    "web.settings.fxserver.reset_data_msg5": "Warning:",
    "web.settings.fxserver.reset_data_msg6": " take note of the current path before proceeding, so you can set it back later if you need to. Current path:",
    "web.settings.fxserver.resetting_data": "Resetting server data path...",
    "web.settings.fxserver.data_folder_desc1": "The full path of the folder that ",
    "web.settings.fxserver.data_folder_desc2": "contains",
    "web.settings.fxserver.data_folder_desc3": " the ",
    "web.settings.fxserver.data_folder_desc4": " folder, usually it's the same place that contains your ",
    "web.settings.fxserver.data_folder_desc5": "Resetting this value will allow you to go back to the Setup page, without deleting any files.",
    "web.settings.fxserver.data_folder_desc6": "This path should start with",
    "web.settings.fxserver.restart_schedule_label": "Restart Schedule",
    "web.settings.fxserver.no_schedule": "No schedule set. Click on the + button to add a time.",
    "web.settings.fxserver.presets": "Presets: ",
    "web.settings.fxserver.per_day": "/day",
    "web.settings.fxserver.add_time_title": "Add Restart Time",
    "web.settings.fxserver.timezone_warn1": "Warning:",
    "web.settings.fxserver.timezone_warn2": " Your server timezone is set to ",
    "web.settings.fxserver.timezone_warn3": ", but your browser timezone is ",
    "web.settings.fxserver.timezone_warn4": ". Make sure to configure the time according to the server timezone.",
    "web.settings.fxserver.restart_schedule_desc1": "At which times of day to restart the server.",
    "web.settings.fxserver.restart_schedule_desc2": "Note:",
    "web.settings.fxserver.restart_schedule_desc3": " Make sure your schedule matches your server time and not your local time.",
    "web.settings.fxserver.quiet_mode_label": "Quiet Mode",
    "web.settings.fxserver.quiet_mode_desc1": "Do not print FXServer's output to the terminal.",
    "web.settings.fxserver.quiet_mode_desc2": "You will still be able to use the Live Console.",
    "web.settings.fxserver.quiet_mode_locked": "This setting is locked and cannot be changed.",
    "web.settings.fxserver.multi_hosting_label": "Multi-Hosting",
    "web.settings.fxserver.multi_hosting_desc": "Activate the Multi-Hosting dashboard page, letting you run and manage multiple separate FXServers simultaneously.",
    "web.settings.fxserver.cfg_path_label": "CFG File Path",
    "web.settings.fxserver.cfg_path_desc1": "The path to your server config file, probably named ",
    "web.settings.fxserver.cfg_path_desc2": "This can either be absolute, or relative to the Server Data folder.",
    "web.settings.fxserver.startup_args_label": "Startup Arguments",
    "web.settings.fxserver.startup_args_desc1": "Additional command-line arguments to pass to the FXServer instance such as NodeJS CLI flags.",
    "web.settings.fxserver.startup_args_desc2": "Warning:",
    "web.settings.fxserver.startup_args_desc3": " You almost certainly should not use this option, commands and convars should be placed in your ",
    "web.settings.fxserver.startup_args_desc4": " instead.",
    "web.settings.fxserver.onesync_label": "OneSync",
    "web.settings.fxserver.onesync_placeholder": "Select OneSync option",
    "web.settings.fxserver.onesync_on": "On (recommended)",
    "web.settings.fxserver.onesync_legacy": "Legacy",
    "web.settings.fxserver.onesync_off": "Off",
    "web.settings.fxserver.onesync_desc1": "Most servers should be using ",
    "web.settings.fxserver.onesync_desc2": "OneSync On",
    "web.settings.fxserver.onesync_desc3": "The other options are considered deprecated and should not be used unless you know what you're doing. For more information, please read the ",
    "web.settings.fxserver.onesync_desc4": "documentation",
    "web.settings.fxserver.autostart_label": "Autostart",
    "web.settings.fxserver.autostart_desc1": "Start the server automatically after ",
    "web.settings.fxserver.autostart_desc2": " starts.",
    "web.settings.fxserver.tolerance_label": "Resource Starting Tolerance",
    "web.settings.fxserver.tolerance_placeholder": "Select...",
    "web.settings.fxserver.tolerance_opt1": "1.5 minutes (default)",
    "web.settings.fxserver.tolerance_opt2": "3 minutes",
    "web.settings.fxserver.tolerance_opt3": "5 minutes",
    "web.settings.fxserver.tolerance_opt4": "10 minutes",
    "web.settings.fxserver.tolerance_desc1": "At server boot, how much time to wait for any single resource to start before restarting the server.",
    "web.settings.fxserver.tolerance_desc2": "Note:",
    "web.settings.fxserver.tolerance_desc3": " If you are getting ",
    "web.settings.fxserver.tolerance_desc4": " errors, increase this value.",

    // Settings: Game Menu Card
    "web.settings.gamemenu.label": "Game Menu",
    "web.settings.gamemenu.desc1": "When enabled, admins will be able to open the menu by typing ",
    "web.settings.gamemenu.desc2": " or using the keybind configured in the FiveM/RedM settings.",
    "web.settings.gamemenu.align_right_label": "Align Menu Right",
    "web.settings.gamemenu.align_right_desc": "Move menu to the right side of the screen.",
    "web.settings.gamemenu.align_right_checked": "Right aligned",
    "web.settings.gamemenu.align_right_unchecked": "Left aligned",
    "web.settings.gamemenu.page_key_label": "Menu Page Switch Key",
    "web.settings.gamemenu.page_key_placeholder": "click here and use the key to change",
    "web.settings.gamemenu.page_key_desc1": "The key used to to switch tabs in the menu.",
    "web.settings.gamemenu.page_key_desc2": "Click above and press any key to change the configuration.",
    "web.settings.gamemenu.page_key_desc3": "Note:",
    "web.settings.gamemenu.page_key_desc4": " The default is ",
    "web.settings.gamemenu.page_key_desc5": ", and you cannot use ",
    "web.settings.gamemenu.page_key_desc6": " or ",
    "web.settings.gamemenu.effect_label": "Player Mode Change Effect",
    "web.settings.gamemenu.effect_desc1": "Play a particle effect and sound when an admin uses NoClip, God Mode, etc.",
    "web.settings.gamemenu.effect_desc2": "Warning:",
    "web.settings.gamemenu.effect_desc3": " This options help prevent admin abuse during PvP by making it visible/audible to all players that an admin is using a special mode. We recommend keeping it enabled.",

    // Settings: Game Notifications Card
    "web.settings.gamenotif.hide_admin_punish_label": "Hide Admin Name In Punishments",
    "web.settings.gamenotif.hide_admin_punish_desc1": "Never show to the players the admin name on ",
    "web.settings.gamenotif.hide_admin_punish_desc2": "Bans",
    "web.settings.gamenotif.hide_admin_punish_desc3": " or ",
    "web.settings.gamenotif.hide_admin_punish_desc4": "Warns",
    "web.settings.gamenotif.hide_admin_punish_desc5": "This information will still be available in the history and logs.",
    "web.settings.gamenotif.hide_admin_punish_checked": "Hidden",
    "web.settings.gamenotif.hide_admin_punish_unchecked": "Visible",
    "web.settings.gamenotif.hide_admin_msg_label": "Hide Admin Name In Messages",
    "web.settings.gamenotif.hide_admin_msg_desc1": "Do not show the admin name on ",
    "web.settings.gamenotif.hide_admin_msg_desc2": "Announcements",
    "web.settings.gamenotif.hide_admin_msg_desc3": " or ",
    "web.settings.gamenotif.hide_admin_msg_desc4": "DMs",
    "web.settings.gamenotif.hide_admin_msg_desc5": "This information will still be available in the live console and logs.",
    "web.settings.gamenotif.hide_announcement_label": "Hide Announcement Notifications",
    "web.settings.gamenotif.hide_announcement_desc1": "Suppresses the display of announcements, allowing you to implement your own announcement via the event ",
    "web.settings.gamenotif.hide_announcement_desc2": "Documentation",
    "web.settings.gamenotif.hide_dm_label": "Hide Direct Message Notification",
    "web.settings.gamenotif.hide_dm_desc1": "Suppresses the display of direct messages, allowing you to implement your own direct message notification via the event ",
    "web.settings.gamenotif.hide_dm_desc2": "Documentation",
    "web.settings.gamenotif.hide_warn_label": "Hide Warning Notification",
    "web.settings.gamenotif.hide_warn_desc1": "Suppresses the display of warnings, allowing you to implement your own warning via the event ",
    "web.settings.gamenotif.hide_warn_desc2": "Documentation",
    "web.settings.gamenotif.hide_restart_label": "Hide Scheduled Restart Warnings",
    "web.settings.gamenotif.hide_restart_desc1": "Suppresses the display of scheduled restart warnings, allowing you to implement your own warning via the event ",
    "web.settings.gamenotif.hide_restart_desc2": "Documentation",

    // Settings: Language Card
    "web.settings.language.hub_title": "Community Languages Hub",
    "web.settings.language.loading_community": "Loading community languages...",
    "web.settings.language.no_packs": "No community language packs available yet. Be the first to share one!",
    "web.settings.language.pack_contains": "Community localization package containing %{count} phrase overrides.",
    "web.settings.language.import_apply": "Import & Apply",
    "web.settings.language.share_title": "Share Your Current Custom Translations",
    "web.settings.language.share_pack_title": "Language Pack Title",
    "web.settings.language.share_pack_placeholder": "e.g. German Casual, Pirate Dialect",
    "web.settings.language.share_author": "Author Name",
    "web.settings.language.share_author_placeholder": "Your Name or Team Name",
    "web.settings.language.share_btn": "Share with Community",
    "web.settings.language.editor_placeholder": "Enter translation text...",
    "web.settings.language.search_placeholder": "Search phrases...",
    "web.settings.language.all_categories": "All Categories",
    "web.settings.language.current_saved": "Current Saved Locale",
    "web.settings.language.base_template": "Base Template",
    "web.settings.language.no_match": "No translation keys match your search criteria.",
    "web.settings.language.desc_custom": "Sets the primary language for chat, console log categories, and bot messaging components. Select Custom to load the modified translations below.",
    "web.settings.language.import_applied_success": "Successfully applied community language \"%{name}\"!",
    "web.settings.language.import_toast": "Importing and applying community language \"%{name}\"...",
    "web.settings.language.err_save_lang": "Failed to update active system language.",
    "web.settings.language.err_import_trans": "Failed to import translations to locale.json.",
    "web.settings.language.err_apply_comm": "Error applying community locale.",
    "web.settings.language.err_fill_share": "Please fill in the Language Title and Author Name.",
    "web.settings.language.share_success": "Your translations have been shared with the community successfully!",
    "web.settings.language.err_share_pack": "Failed to share language pack.",
    "web.settings.language.err_connect_comm": "Failed to connect to community backend database.",
    "web.settings.language.err_load_keys": "Failed to load translation keys.",
    "web.settings.language.updating_system_lang": "Updating system language...",
    "web.settings.language.system_lang_updated": "Primary system language updated successfully!",
    "web.settings.language.err_save_lang_setting": "Failed to save language setting.",
    "web.settings.language.custom_locale_meta": "Custom Locale",
    "web.settings.language.err_save_trans": "Error saving translations.",
    "web.settings.language.err_save_trans_generic": "An error occurred during translation save.",
    "web.settings.language.saving_custom_trans": "Saving custom translations to locale.json...",
    "web.settings.language.custom_trans_saved": "Custom translation file saved successfully!",
    "web.settings.language.alert_editor_desc": "All modified fields will be compiled and written dynamically to your server's custom locale.json file. Ensure your active language above is set to Custom to load these templates.",

    // Settings: Theme Card
    "web.settings.theme.library_title": "Community Themes Library",
    "web.settings.theme.loading_community": "Loading community themes database...",
    "web.settings.theme.no_themes": "No community themes uploaded yet. Be the first to share one!",
    "web.settings.theme.apply_theme_toast": "Applied community theme \"%{name}\"!",
    "web.settings.theme.err_select_share": "Please select a theme to share.",
    "web.settings.theme.err_enter_author": "Please enter your name as the author.",
    "web.settings.theme.err_not_found": "Theme not found.",
    "web.settings.theme.err_failed_share": "Failed to share theme.",
    "web.settings.theme.err_connect_comm": "Failed to connect to community backend database.",
    "web.settings.theme.share_success": "Theme shared to the community successfully!",
    "web.settings.theme.copied_hex_toast": "HEX Color %{hex} copied to clipboard!",
    "web.settings.theme.saved_toast": "Theme settings saved.",
    "web.settings.theme.dark_scheme": "Dark Scheme",
    "web.settings.theme.light_scheme": "Light Scheme",
    "web.settings.theme.delete_theme_title": "Delete Custom Theme",
    "web.settings.theme.custom_suffix": " (Custom)",
    "web.settings.theme.deleted_toast": "Theme \"%{name}\" deleted.",
    "web.settings.theme.by_author": "by %{author}",
    "web.settings.theme.canvas": "Canvas",
    "web.settings.theme.accent": "Accent",
    "web.settings.theme.applied": "Applied",
    "web.settings.theme.apply": "Apply",
    "web.settings.theme.hex_format": "HEX Format",
    "web.settings.theme.copy_hex_color": "Copy HEX color",
    "web.settings.theme.theme_id_label": "Theme ID (Lowercase, no spaces)",
    "web.settings.theme.display_label": "Display Label",
    "web.settings.theme.theme_json_copied_toast": "Theme JSON copied to clipboard!",
    "web.settings.theme.err_valid_name": "Please enter a valid unique theme name.",
    "web.settings.theme.err_enter_label": "Please enter a theme label.",
    "web.settings.theme.err_already_exists": "A theme with this name already exists.",
    "web.settings.theme.theme_created_toast": "Theme \"%{label}\" created and applied successfully!",
    "web.settings.theme.err_missing_fields": "Missing required fields: 'name', 'isDark', 'style'.",
    "web.settings.theme.theme_imported_success": "Theme \"%{label}\" imported successfully!",
    "web.settings.theme.err_parse_json": "Failed to parse theme JSON: %{error}",
    "web.settings.theme.active_theme_desc": "Choose from standard built-in themes, customized preset themes, or click to load custom themes stored in this browser session.",
    "web.settings.theme.comm_themes_desc": "Browse, download, and apply theme customization packages created and shared by other vibeSM community administrators.",
    "web.settings.theme.share_theme_label": "Share Theme to Community",
    "web.settings.theme.share_select_label": "Select Theme to Share",
    "web.settings.theme.share_select_placeholder": "Select one of your custom themes...",
    "web.settings.theme.share_author_label": "Author Name",
    "web.settings.theme.share_author_placeholder": "Your Name or Server Name",
    "web.settings.theme.share_btn": "Upload & Share Theme",
    "web.settings.theme.share_desc": "Publish your customized themes directly to the shared community catalog for other administrators worldwide to fetch and enjoy.",
    "web.settings.theme.creator_dark_scheme_label": "Use Dark Scheme styling (recommends dark text on light accents)",
    "web.settings.theme.creator_hsl_title": "Active Variable HSL Configuration",
    "web.settings.theme.creator_accent_label": "Primary Accent",
    "web.settings.theme.creator_bg_label": "Core Background",
    "web.settings.theme.creator_card_label": "Card Backdrop",
    "web.settings.theme.creator_fg_label": "Text/Foreground",
    "web.settings.theme.creator_card_fg_label": "Card Text",
    "web.settings.theme.creator_border_label": "Hairline Borders",
    "web.settings.theme.creator_btn": "Create & Apply Theme",
    "web.settings.theme.creator_desc": "Tweak color variable parameters visually in HSL, HSV, or HEX units to build a premium custom dynamic theme. Outlines, shadows, and secondary configurations are mathematically balanced automatically.",
    "web.settings.theme.import_export_label": "Import & Export Theme",
    "web.settings.theme.export_json_label": "Active Theme JSON (Export)",
    "web.settings.theme.export_desc": "Click inside the box to copy the active theme JSON setup to share with other vibeSM/txAdmin admins.",
    "web.settings.theme.import_json_label": "Paste Theme JSON (Import)",
    "web.settings.theme.import_btn": "Import Theme",

    // History Page & Search/Table Components
    "web.history.title_total_warns": "Total Warns",
    "web.history.title_new_warns_7d": "New Warns Last 7d",
    "web.history.title_total_bans": "Total Bans",
    "web.history.title_new_bans_7d": "New Bans Last 7d",
    "web.history.search_type": "Search Type",
    "web.history.search_by": "Search by %{type}",
    "web.history.filter_any_type": "Any type",
    "web.history.filter_bans": "Bans",
    "web.history.filter_warns": "Warns",
    "web.history.filter_any_admin": "By any admin",
    "web.history.filter_admin_placeholder": "Filter by admin",
    "web.history.more": "More",
    "web.history.bulk_remove": "Bulk Remove",
    "web.history.ban_templates": "Ban Templates",
    "web.history.row_unknown": "unknown",
    "web.history.err_req_failed": "Request failed.",
    "web.history.err_req_failed_with": "Request failed: %{error}",
    "web.history.err_fetch_failed": "Failed to fetch more data: %{error}",
    "web.history.last_row_error": "Error: %{error}",
    "web.history.last_row_try_again": "Try again?",
    "web.history.reached_end": "You have reached the end of the list.",
    "web.history.no_actions": "No actions found.",
    "web.history.bug_report_1": "You've found the end of the rainbow, but there's no pot of gold here.",
    "web.history.bug_report_2": "(this is a bug, please report it in %{discord})",
    "web.history.bug_report_2_prefix": "(this is a bug, please report it in ",
    "web.history.bug_report_2_suffix": ")",
    "web.history.header_action": "Action",
    "web.history.header_player": "Player",
    "web.history.header_reason": "Reason",
    "web.history.header_author": "Author",
    "web.history.header_date_time": "Date Time",
    "web.history.search_type_action_id": "Action ID",
    "web.history.search_type_action_id_desc": "Search actions by their ID.",
    "web.history.search_type_reason": "Reason",
    "web.history.search_type_reason_placeholder": "Enter part of the reason to search for",
    "web.history.search_type_reason_desc": "Search actions by their reason contents.",
    "web.history.search_type_player_ids": "Player IDs",
    "web.history.search_type_player_ids_placeholder": "License, Discord, Steam, etc.",
    "web.history.search_type_player_ids_desc": "Search actions by their player IDs separated by a comma.",

    // Live Console Component
    "web.liveconsole.title": "Live Console",
    "web.liveconsole.search.no_results": "No results",
    "web.liveconsole.search.placeholder": "Search string",
    "web.liveconsole.search.case_sensitive": "Case Sensitive",
    "web.liveconsole.search.whole_word": "Whole Word",
    "web.liveconsole.search.regex": "Regex",
    "web.liveconsole.search.previous": "Previous",
    "web.liveconsole.search.next": "Next",
    "web.liveconsole.search.close": "Close",
    "web.liveconsole.footer.err_no_perm": "You do not have permission to write to the console.",
    "web.liveconsole.footer.err_not_running": "The server is not running.",
    "web.liveconsole.footer.err_lost_connection": "Socket connection lost.",
    "web.liveconsole.footer.placeholder": "Type a command...",
    "web.liveconsole.footer.saved": "Saved",
    "web.liveconsole.footer.search": "Search",
    "web.liveconsole.footer.clear": "Clear",
    "web.liveconsole.footer.download": "Download",
    "web.liveconsole.bookmark.close": "Close",
    "web.liveconsole.bookmark.save": "Save",
    "web.liveconsole.bookmark.remove": "Remove",
    "web.liveconsole.bookmark.history_cleared": "History cleared",
    "web.liveconsole.bookmark.save_command": "Save Command",
    "web.liveconsole.bookmark.prompt_msg": "Enter the command to save:",
    "web.liveconsole.bookmark.history_title": "History",
    "web.liveconsole.bookmark.clear_history": "Clear History",
    "web.liveconsole.bookmark.history_empty": "The command history is empty.",
    "web.liveconsole.bookmark.saved_title": "Saved",
    "web.liveconsole.bookmark.add_new": "Add New",
    "web.liveconsole.bookmark.saved_empty_1": "There are no saved commands.",
    "web.liveconsole.bookmark.saved_empty_2": "To save a command, click the star icon next to it.",
    "web.liveconsole.err_copy_failed_sad": "Failed to copy to clipboard :(",
    "web.liveconsole.err_copy_failed": "Failed to copy to clipboard:",
    "web.liveconsole.console_cleared": "[console cleared]",
    "web.liveconsole.connecting": "Connecting...",

    // Players Page
    "web.players.title_total": "Total Players",
    "web.players.title_played_24h": "Players Last 24h",
    "web.players.title_joined_24h": "New Players Last 24h",
    "web.players.title_joined_7d": "New Players Last 7d",
    "web.players.search_type": "Search Type",
    "web.players.search_by": "Search by %{type}",
    "web.players.remember_option": "Remember Option",
    "web.players.filters_title": "Search Filters",
    "web.players.clear_filters": "Clear Filters",
    "web.players.no_filters": "No filters",
    "web.players.filter_count": "%{smart_count} Filter |||| %{smart_count} Filters",
    "web.players.more": "More",
    "web.players.ban_identifiers": "Ban Identifiers",
    "web.players.prune_players": "Prune Players/HWIDs",
    "web.players.last_row_error": "Error: %{error}",
    "web.players.last_row_try_again": "Try again?",
    "web.players.reached_end": "You have reached the end of the list.",
    "web.players.no_players": "No players found.",
    "web.players.err_req_failed": "Request failed.",
    "web.players.err_req_failed_with": "Request failed: %{error}",
    "web.players.err_fetch_failed": "Failed to fetch more data: %{error}",
    "web.players.header_display_name": "Display Name",
    "web.players.header_play_time": "Play Time",
    "web.players.header_first_joined": "First Joined",
    "web.players.header_last_connection": "Last Connection",
    "web.players.search_type_name": "Name",
    "web.players.search_type_name_placeholder": "Enter a player name",
    "web.players.search_type_name_desc": "Search players by their last display name.",
    "web.players.search_type_notes": "Notes",
    "web.players.search_type_notes_placeholder": "Enter part of the note to search for",
    "web.players.search_type_notes_desc": "Search players by their profile notes contents.",
    "web.players.search_type_player_ids": "Player IDs",
    "web.players.search_type_player_ids_placeholder": "License, Discord, Steam, etc.",
    "web.players.search_type_player_ids_desc": "Search players by their IDs separated by a comma.",
    "web.players.filter_is_admin": "Is Admin",
    "web.players.filter_is_online": "Is Online",
    "web.players.filter_is_whitelisted": "Has Whitelisted ID",
    "web.players.filter_has_note": "Has Profile Notes",

    // Player Drops
    "web.player_drops.expected_drops": "Expected Player Drops",
    "web.player_drops.unexpected_drops": "Unexpected Player Drops",
    "web.player_drops.filter_placeholder": "Filter by admin",
    "web.player_drops.days": "Days",
    "web.player_drops.hours": "Hours",
    "web.player_drops.loading": "Loading...",
    "web.player_drops.overview": "Overview",
    "web.player_drops.crash_reasons": "Crash Reasons",
    "web.player_drops.environment_changes": "Environment Changes",
    "web.player_drops.period_from_to": "Period from %{start} to %{end}.",
    "web.player_drops.period_prefix": "Period from ",
    "web.player_drops.period_to": " to ",
    "web.player_drops.period_suffix": ".",
    "web.player_drops.period_overview": "Period Overview",
    "web.player_drops.resource_kicks": "Resource Kicks",
    "web.player_drops.top_50": "Top ~50",
    "web.player_drops.top_100": "Top ~100",
    "web.player_drops.show_all": "Show All",
    "web.player_drops.sort_by_count": "Sort by Count",
    "web.player_drops.group_reasons": "Group Reasons",
    "web.player_drops.no_drops_window": "No player drops within this time window.",
    "web.player_drops.render_error": "Render Error: %{error}",
    "web.player_drops.retry": "Retry",
    "web.player_drops.no_disconnects_recent": "No players disconnected from your server recently.",
    "web.player_drops.crashes.pct_title": "Percent of all crashes",
    "web.player_drops.crashes.count_title": "Crash count",
    "web.player_drops.crashes.no_crashes": "No player crashes within this time window.",
    "web.player_drops.crashes.header_count": "Count",
    "web.player_drops.crashes.header_reason": "Crash Reason",
    "web.player_drops.crashes.showing_top": "Showing the top %{shown} out of %{total} reasons which account for %{pct} of all crashes.",
    "web.player_drops.crashes.remaining_reasons": "The remaining %{remaining} reasons account for %{pct} of all crashes.",
    "web.player_drops.crashes.show_all_btn": "Show All!",
    "web.player_drops.changes.switched_from_to": "Switched from %{old} to %{new}",
    "web.player_drops.changes.switched_prefix": "Switched from ",
    "web.player_drops.changes.switched_middle": " to ",
    "web.player_drops.changes.removed": "Removed: ",
    "web.player_drops.changes.added": "Added: ",
    "web.player_drops.changes.updated": "Updated: ",
    "web.player_drops.changes.type_fxs": "Changed FXServer version",
    "web.player_drops.changes.type_game": "Changed game version",
    "web.player_drops.changes.type_resources": "Changed boot resources",
    "web.player_drops.changes.no_changes": "No environmental changes within this time window.",
    "web.player_drops.resources.no_kicks": "No players kicked by resources within this time window.",
    "web.player_drops.err_loading": "Error loading data.",
    "web.player_drops.category.player.label": "Player",
    "web.player_drops.category.player.desc": "Player left by quitting the game, leaving the server or other normal means.",
    "web.player_drops.category.resource.label": "Resource",
    "web.player_drops.category.resource.desc": "Player kicked out of the server by a resource.",
    "web.player_drops.category.timeout.label": "Timeout",
    "web.player_drops.category.timeout.desc": "Player connection timed out due to networking issues or client crash.",
    "web.player_drops.category.crash.label": "Crash",
    "web.player_drops.category.crash.desc": "Player left due to a game crash, but was still able to inform the server the crash reason.",
    "web.player_drops.category.security.label": "Security",
    "web.player_drops.category.security.desc": "Player kicked out of the server due to suspect behavior such as sending too many commands or losing connection to the Cfx.re backend services.",
    "web.player_drops.category.unknown.label": "Unknown",
    "web.player_drops.category.unknown.desc": "Player left the server for an unknown reason.",

    // Ban Templates
    "web.ban_templates.remove_template": "Remove Template",
    "web.ban_templates.remove": "Remove",
    "web.ban_templates.confirm_remove": "Are you sure you want to remove this ban template?",
    "web.ban_templates.unknown_error": "unknown error",
    "web.ban_templates.err_loading": "Error loading: %{error}",
    "web.ban_templates.try_again": "Try again?",
    "web.ban_templates.saving": "Saving...",
    "web.ban_templates.err_saving": "Error saving: %{error}",
    "web.ban_templates.saved": "Saved.",
    "web.ban_templates.loading": "Loading...",
    "web.ban_templates.desc_para1": "Here you can configure ban reasons and durations that will appear as dropdown options when banning a player.",
    "web.ban_templates.desc_para2": "This is useful for common reasons that happen frequently, like violation of your server rules.",
    "web.ban_templates.tip_drag": "TIP: You can also drag and drop to reorder the list.",
    "web.ban_templates.perms_required_prefix": "You need the ",
    "web.ban_templates.perms_required_suffix": " permission to edit these reasons.",
    "web.ban_templates.perms_settings_change": "Settings: Change",
    "web.ban_templates.configured_reasons": "Configured reasons: %{count}",
    "web.ban_templates.no_reasons": "No reasons configured yet.",
    "web.ban_templates.title": "Ban Templates",
    "web.ban_templates.parent_name": "Settings",
    "web.ban_templates.toast_reason_len": "Reason must be at least 3 characters long",
    "web.ban_templates.toast_custom_pos": "Custom duration must be a positive number",
    "web.ban_templates.edit_template": "Edit Template",
    "web.ban_templates.add_template": "Add Template",
    "web.ban_templates.label_reason": "Reason",
    "web.ban_templates.placeholder_reason": "The reason for the ban, rule violated, etc.",
    "web.ban_templates.label_duration": "Duration",
    "web.ban_templates.select_duration_placeholder": "Select Duration",
    "web.ban_templates.duration_custom": "Custom (set below)",
    "web.ban_templates.duration_2h": "2 HOURS",
    "web.ban_templates.duration_8h": "8 HOURS",
    "web.ban_templates.duration_1d": "1 DAY",
    "web.ban_templates.duration_2d": "2 DAYS",
    "web.ban_templates.duration_1w": "1 WEEK",
    "web.ban_templates.duration_2w": "2 WEEKS",
    "web.ban_templates.duration_permanent": "Permanent",
    "web.ban_templates.unit_hours": "1 hour |||| %{smart_count} hours",
    "web.ban_templates.unit_days": "1 day |||| %{smart_count} days",
    "web.ban_templates.unit_weeks": "1 week |||| %{smart_count} weeks",
    "web.ban_templates.unit_months": "1 month |||| %{smart_count} months",
    "web.ban_templates.select_unit_hours": "HOURS",
    "web.ban_templates.select_unit_days": "DAYS",
    "web.ban_templates.select_unit_weeks": "WEEKS",
    "web.ban_templates.select_unit_months": "MONTHS",
    "web.ban_templates.save_changes": "Save changes",
    "web.ban_templates.add_new_reason": "Add New Reason",

    // Ban Form (player modal)
    "web.ban_form.no_templates": "You do not have any template configured.",
    "web.ban_form.add_ban_template": "Add Ban Template",
};

// Initialize phrases dictionary injected by the backend merged with default fallbacks
const initialPhrases = {
    ...reactDefaultPhrases,
    ...(window.txConsts?.phrases || {})
};

export const phrasesAtom = atom<Record<string, any>>(initialPhrases);
export const languageAtom = atom<string>(window.txConsts?.language || 'en');

/**
 * A helper to resolve dot-notation path inside a nested object
 */
export function resolvePhrasePath(obj: any, path: string): any {
    if (!obj || !path) return undefined;
    return path.split('.').reduce((acc, part) => {
        if (acc && typeof acc === 'object') {
            return acc[part];
        }
        return undefined;
    }, obj);
}

/**
 * Custom translation hook
 */
export const useTranslation = () => {
    const phrases = useAtomValue(phrasesAtom);

    const t = (key: string, options?: Record<string, any>): string => {
        // First try to resolve nested key path
        let phrase = resolvePhrasePath(phrases, key);

        // If not found, check direct key
        if (phrase === undefined) {
            phrase = phrases[key];
        }

        // If still not found, check default react phrases
        if (phrase === undefined) {
            phrase = reactDefaultPhrases[key];
        }

        // If still not found, return the key as fallback
        if (phrase === undefined || phrase === null) {
            return key;
        }

        let phraseStr = String(phrase);

        // Handle plurals if smart_count is provided (e.g. "phrase |||| plural phrase")
        if (options && typeof options.smart_count === 'number') {
            const parts = phraseStr.split('||||');
            if (parts.length > 1) {
                phraseStr = options.smart_count === 1 ? parts[0].trim() : parts[1].trim();
            }
        }

        // Interpolate placeholders like %{variable}
        if (options) {
            for (const [k, v] of Object.entries(options)) {
                phraseStr = phraseStr.replace(new RegExp(`%\\{${k}\\}`, 'g'), String(v));
            }
        }

        return phraseStr;
    };

    return { t };
};
