/**
 * This script patches de.json with German translations for all remaining English strings.
 * Run: node scripts/translate-de.js
 */
const fs = require('fs');
const path = require('path');

const deJsonPath = path.resolve(__dirname, '..', 'locale', 'de.json');
const deJson = JSON.parse(fs.readFileSync(deJsonPath, 'utf-8'));

// Helper to set a nested value by dot-path
function setNestedValue(obj, dotPath, value) {
    const keys = dotPath.split('.');
    let cur = obj;
    for (let i = 0; i < keys.length - 1; i++) {
        if (!cur[keys[i]]) cur[keys[i]] = {};
        cur = cur[keys[i]];
    }
    cur[keys[keys.length - 1]] = value;
}

// All translations keyed by their nested dot path from the root of the JSON
const translations = {
    // web.settings
    "web.settings.enabled": "Aktiviert",
    "web.settings.disabled": "Deaktiviert",

    // web.settings.bans
    "web.settings.bans.checking": "Ban-Prüfung",
    "web.settings.bans.checking_desc": "Aktiviert die Prüfung des Ban-Status beim Beitritt eines Spielers. Hinweis: vibeSM-Bans funktionieren nicht, wenn diese Option deaktiviert ist.",
    "web.settings.bans.templates": "Bannvorlagen",
    "web.settings.bans.templates_edit": "Bannvorlagen bearbeiten",
    "web.settings.bans.templates_desc": "Konfiguriere Banngründe und -dauern, die als Dropdown-Optionen beim Bannen eines Spielers angezeigt werden. Dies ist nützlich für häufig vorkommende Gründe, wie z. B. Verstöße gegen deine Serverregeln.",
    "web.settings.bans.rejection": "Ban-Ablehnungsnachricht",
    "web.settings.bans.rejection_placeholder": "Du kannst http://discord.gg/example beitreten, um diesen Ban anzufechten.",
    "web.settings.bans.rejection_desc": "Optionale Nachricht, die einem Spieler in der Ablehnungsnachricht angezeigt wird, wenn er versucht, sich zu verbinden, während er gebannt ist. Wenn du ein Ban-Einspruchsverfahren hast, kannst du dieses Feld nutzen, um die Spieler zu informieren.",
    "web.settings.bans.validation_title": "Die Ban-Ablehnungsnachricht ist zu lang.",
    "web.settings.bans.validation_msg": "Die Nachricht darf maximal 512 Zeichen lang sein.",
    "web.settings.bans.hwid": "Erforderliche Ban-HWID-Übereinstimmungen",
    "web.settings.bans.hwid_desc": "Diese Option konfiguriert, wie viele HWID-Token zwischen einem Spieler und einem bestehenden Ban übereinstimmen müssen, damit der Spielerbeitritt blockiert wird, oder kann HWID-Bans vollständig deaktivieren. Da Hardware-ID-Token nicht garantiert einzigartig sind, besteht die Möglichkeit, dass Token zweier Spieler übereinstimmen, ohne dass sie miteinander verwandt sind. Hinweis: Die meisten Spieler haben 3 bis 6 HWID-Token.",
    "web.settings.bans.hwid_opt1": "1 - empfohlen",
    "web.settings.bans.hwid_opt2": "2 - locker",
    "web.settings.bans.hwid_opt3": "3 - sehr locker",
    "web.settings.bans.hwid_opt4": "4 - praktisch deaktiviert",
    "web.settings.bans.hwid_opt0": "HWID-Bans deaktivieren",

    // web.settings.queue
    "web.settings.queue.enabled": "Verbindungswarteschlange",
    "web.settings.queue.enabled_desc": "Verbindungswarteschlange aktivieren, wenn der Server voll ist oder eine Warteschlange besteht.",
    "web.settings.queue.priority_roles": "Prioritäts-Discord-Rollen",
    "web.settings.queue.priority_roles_desc": "Discord-Rollen-IDs, die Priorität in der Verbindungswarteschlange erhalten (durch Komma getrennt).",
    "web.settings.queue.team_roles": "Team-/Staff-Discord-Rollen",
    "web.settings.queue.team_roles_desc": "Discord-Rollen-IDs für Teammitglieder, die die Verbindungswarteschlange komplett umgehen (durch Komma getrennt).",
    "web.settings.queue.max_slots": "Benutzerdefinierte Max-Slots",
    "web.settings.queue.max_slots_desc": "Maximale Slots für das Warteschlangensystem überschreiben (0 für automatische Erkennung aus FXServer maxClients).",
    "web.settings.queue.priority_label": "Prioritätsrollen-Bezeichnung",
    "web.settings.queue.priority_label_desc": "Bezeichnung, die im Warteschlangen-Text für Spieler mit Prioritätsrolle angezeigt wird.",
    "web.settings.queue.standard_label": "Standard-Rollen-Bezeichnung",
    "web.settings.queue.standard_label_desc": "Bezeichnung, die im Warteschlangen-Text für normale Spieler angezeigt wird.",
    "web.settings.queue.msg_template": "Warteschlangen-Konsolennachricht-Vorlage",
    "web.settings.queue.msg_template_desc": "Benutzerdefiniertes Konsolennachrichten-Layout, das im Verbindungs-Fallback-Dialog angezeigt wird. Unterstützt Platzhalter: {{position}}, {{queueLength}}, {{queueType}}, {{activePlayers}}, {{maxSlots}}, {{elapsedTime}}.",
    "web.settings.queue.card_template": "Adaptive Card Vorlage JSON",
    "web.settings.queue.card_template_desc": "Benutzerdefiniertes AdaptiveCard-JSON, das Spielern in der Warteschlange angezeigt wird. Unterstützt Platzhalter: {{playerName}}, {{avatarURL}}, {{position}}, {{queueLength}}, {{elapsedTime}}, {{queueType}}.",
    "web.settings.queue.val_priority_roles_title": "Ungültige Prioritäts-Discord-Rollen-ID(s).",
    "web.settings.queue.val_team_roles_title": "Ungültige Team-Discord-Rollen-ID(s).",
    "web.settings.queue.val_roles_msg": "Die folgenden Rollen-ID(s) sind ungültig: \\n%{roles}",
    "web.settings.queue.val_json_title": "Ungültiges Adaptive Card JSON",
    "web.settings.queue.val_json_msg": "Bitte überprüfe, ob das JSON gültig ist: %{error}",

    // web.settings.general
    "web.settings.general.server_name": "Servername",
    "web.settings.general.server_name_required": "Der Servername ist erforderlich.",
    "web.settings.general.server_name_too_big": "Der Servername ist zu lang.",
    "web.settings.general.server_name_desc1": "Ein ",
    "web.settings.general.server_name_desc2": "kurzer",
    "web.settings.general.server_name_desc3": " Servername, der in der vibeSM-Oberfläche und Server-/Discord-Nachrichten verwendet wird.",
    "web.settings.general.server_name_desc4": "Der Name muss zwischen 1 und 18 Zeichen lang sein.",
    "web.settings.general.language": "Sprache",
    "web.settings.general.language_desc1": "Die Sprache, die in Chat-/Discord-Nachrichten verwendet wird.",
    "web.settings.general.language_desc2": "Du kannst die Phrasen/Wörter anpassen, indem du die ",
    "web.settings.general.language_desc3": "-Option verwendest.",
    "web.settings.general.language_desc4": "Für weitere Informationen lies bitte die ",
    "web.settings.general.language_desc5": "Dokumentation",

    // web.settings.whitelist
    "web.settings.whitelist.label": "Whitelist-Modus",
    "web.settings.whitelist.mode_disabled": "Deaktiviert",
    "web.settings.whitelist.mode_disabled_desc": "Kein Whitelist-Status wird von vibeSM geprüft.",
    "web.settings.whitelist.mode_admin": "Nur Admins (Wartungsmodus)",
    "web.settings.whitelist.mode_admin_desc1": "Erlaubt den Serverbeitritt nur, wenn deine ",
    "web.settings.whitelist.mode_admin_desc2": " Identifier einem vibeSM-Administrator zugeordnet sind. Auch bekannt als Wartungsmodus.",
    "web.settings.whitelist.mode_discord_member": "Discord-Server-Mitglied",
    "web.settings.whitelist.mode_discord_member_desc1": "Prüft, ob der beitretende Spieler einen ",
    "web.settings.whitelist.mode_discord_member_desc2": "-Identifier hat und im Discord-Server vorhanden ist, der im Discord-Tab konfiguriert wurde.",
    "web.settings.whitelist.mode_discord_roles": "Discord-Server-Rollen",
    "web.settings.whitelist.mode_discord_roles_desc1": "Prüft, ob der beitretende Spieler einen ",
    "web.settings.whitelist.mode_discord_roles_desc2": "-Identifier hat, im konfigurierten Discord-Server vorhanden ist und mindestens eine der unten angegebenen Rollen besitzt.",
    "web.settings.whitelist.mode_approved": "Genehmigte Lizenz",
    "web.settings.whitelist.mode_approved_desc1": "Der Spieler-",
    "web.settings.whitelist.mode_approved_desc2": "-Identifier muss von einem vibeSM-Administrator auf die Whitelist gesetzt werden. Dies kann über die ",
    "web.settings.whitelist.mode_approved_desc3": "Whitelist-Seite",
    "web.settings.whitelist.mode_approved_desc4": " oder den ",
    "web.settings.whitelist.mode_approved_desc5": " Discord-Bot-Slash-Befehl erfolgen.",
    "web.settings.whitelist.mode_external": "Externe Allowlist-Ressource",
    "web.settings.whitelist.mode_external_desc": "Wähle diese Option, wenn du ein externes Allowlist-System verwendest, um zu verwalten, welche Spieler dem Server beitreten können.",
    "web.settings.whitelist.note": "Hinweis:",
    "web.settings.whitelist.note_desc": " Spieler sehen das Symbol \"Allowlist aktiviert\" in der Serverliste.",
    "web.settings.whitelist.rejection_label": "Whitelist-Ablehnungsnachricht",
    "web.settings.whitelist.rejection_placeholder": "Bitte tritt http://discord.gg/example bei und beantrage die Whitelist.",
    "web.settings.whitelist.rejection_desc1": "Optionale Nachricht, die einem Spieler in der Ablehnungsnachricht angezeigt wird, wenn er versucht, sich zu verbinden, ohne auf der Whitelist zu stehen.",
    "web.settings.whitelist.rejection_desc2": "Wenn du ein Discord-Whitelist-Verfahren hast, füge hier einen Einladungslink ein.",
    "web.settings.whitelist.allowlist_instructions_label": "Allowlist-Anweisungen",
    "web.settings.whitelist.allowlist_instructions_placeholder": "Anweisungen eingeben, wie man auf die Allowlist kommt...",
    "web.settings.whitelist.allowlist_instructions_desc1": "Anweisungen, wie man auf die Allowlist kommt. Dies aktiviert die ",
    "web.settings.whitelist.allowlist_instructions_desc2": "-ConVar, wenn ausgefüllt.",
    "web.settings.whitelist.discord_roles_label": "Whitelistete Discord-Rollen",
    "web.settings.whitelist.discord_roles_placeholder": "000000000000000000, 000000000000000000",
    "web.settings.whitelist.discord_roles_desc1": "Die ID der Discord-Rollen, die für den Serverbeitritt whitelistet sind.",
    "web.settings.whitelist.discord_roles_desc2": "Dieses Feld unterstützt mehrere Rollen, durch Komma getrennt.",
    "web.settings.whitelist.discord_roles_desc3": "Erfordert, dass der Whitelist-Modus auf \"Discord-Server-Rollen\" eingestellt ist.",
    "web.settings.whitelist.val_rejection_title": "Die Whitelist-Ablehnungsnachricht ist zu lang.",
    "web.settings.whitelist.val_rejection_msg": "Die Nachricht darf maximal 512 Zeichen lang sein.",
    "web.settings.whitelist.val_bot_required_title": "Discord-Bot ist erforderlich.",
    "web.settings.whitelist.val_bot_required_msg": "Du musst den Discord-Bot im Discord-Tab aktivieren, um Discord-basierte Whitelist-Modi zu verwenden.",
    "web.settings.whitelist.val_roles_required_title": "Discord-Rollen sind erforderlich.",
    "web.settings.whitelist.val_roles_required_msg": "Du musst mindestens eine Discord-Rollen-ID angeben, um den Whitelist-Modus \"Discord-Server-Rollen\" zu verwenden.",
    "web.settings.whitelist.val_invalid_roles_title": "Ungültige Discord-Rollen-ID(s).",
    "web.settings.whitelist.val_invalid_roles_msg": "Die folgenden Discord-Rollen-ID(s) sind ungültig: \\n%{roles}",

    // web.settings.discord
    "web.settings.discord.bot_label": "Discord-Bot",
    "web.settings.discord.bot_desc": "Discord-Integration aktivieren.",
    "web.settings.discord.token_label": "Token",
    "web.settings.discord.token_placeholder": "xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "web.settings.discord.token_desc1": "Um einen Token zu erhalten und den Bot deinem Server hinzuzufügen, folge diesen beiden Anleitungen:",
    "web.settings.discord.token_desc2": "Eine Bot-Anwendung einrichten",
    "web.settings.discord.token_desc3": "Deinen Bot zu Servern hinzufügen",
    "web.settings.discord.token_desc4": "Verwende nicht denselben Token für einen anderen Bot.",
    "web.settings.discord.token_desc5": "Der Bot benötigt das",
    "web.settings.discord.token_desc6": "Server Members",
    "web.settings.discord.token_desc7": "-Intent, das im",
    "web.settings.discord.token_desc8": "Discord Developer Portal",
    "web.settings.discord.guild_label": "Guild-/Server-ID",
    "web.settings.discord.guild_placeholder": "000000000000000000",
    "web.settings.discord.guild_desc1": "Die ID des Discord-Servers (auch als Discord-Guild bekannt).",
    "web.settings.discord.guild_desc2": "Um die Server-ID zu erhalten, gehe zu den Discord-Einstellungen und",
    "web.settings.discord.guild_desc3": " aktiviere den Entwicklermodus",
    "web.settings.discord.guild_desc4": ", dann klicke mit der rechten Maustaste auf das Server-Symbol und wähle \"ID kopieren\".",
    "web.settings.discord.warnings_channel_label": "Warnungen-Kanal-ID",
    "web.settings.discord.warnings_channel_placeholder": "000000000000000000",
    "web.settings.discord.warnings_channel_desc1": "Die ID des Kanals, an den Ankündigungen gesendet werden (z. B. Server-Neustarts).",
    "web.settings.discord.warnings_channel_desc2": "Leer lassen, um diese Funktion zu deaktivieren.",
    "web.settings.discord.warnings_channel_desc3": "Um die Kanal-ID zu erhalten, gehe zu den Discord-Einstellungen und",
    "web.settings.discord.warnings_channel_desc4": " aktiviere den Entwicklermodus",
    "web.settings.discord.warnings_channel_desc5": ", dann klicke mit der rechten Maustaste auf den Kanalnamen und wähle \"ID kopieren\".",
    "web.settings.discord.allow_dangerous_perms_label": "Gefährliche Berechtigungen erlauben",
    "web.settings.discord.allow_dangerous_perms_desc1": "Erlaubt dem Discord-Bot, auch mit potenziell gefährlichen administrativen Berechtigungen zu starten.",
    "web.settings.discord.allow_dangerous_perms_desc2": "Warnung: Es wird aus Sicherheitsgründen empfohlen, dies deaktiviert zu lassen.",
    "web.settings.discord.allow_dangerous_perms_allowed": "Erlaubt",
    "web.settings.discord.allow_dangerous_perms_forbidden": "Verboten",
    "web.settings.discord.activity_type_label": "Aktivitätstyp",
    "web.settings.discord.activity_type_placeholder": "Typ auswählen...",
    "web.settings.discord.activity_type_desc": "Der Aktivitätstyp, der in der Discord-Präsenz des Bots angezeigt wird.",
    "web.settings.discord.activity_type_playing": "Spielt",
    "web.settings.discord.activity_type_streaming": "Streamt",
    "web.settings.discord.activity_type_listening": "Hört zu",
    "web.settings.discord.activity_type_watching": "Schaut zu",
    "web.settings.discord.activity_type_competing": "Tritt an",
    "web.settings.discord.activity_desc_label": "Aktivitätsbeschreibung",
    "web.settings.discord.activity_desc_placeholder": "[{{players}}/{{maxClients}}] auf {{serverName}}",
    "web.settings.discord.activity_desc_desc1": "Der Aktivitäts-Statustext. Unterstützt folgende Platzhalter:",
    "web.settings.discord.activity_desc_desc2": "Online-Spieleranzahl",
    "web.settings.discord.activity_desc_desc3": "Maximale Spielerkapazität",
    "web.settings.discord.activity_desc_desc4": "Der Servername",
    "web.settings.discord.activity_desc_desc5": "Leer lassen für den Standard:",
    "web.settings.discord.activity_desc_starting_label": "Aktivitätsbeschreibung (Server startet)",
    "web.settings.discord.activity_desc_starting_placeholder": "Server startet...",
    "web.settings.discord.activity_desc_starting_desc1": "Der Aktivitäts-Statustext, der angezeigt wird, während der FXServer hochfährt/startet.",
    "web.settings.discord.activity_desc_starting_desc2": "Leer lassen für den Standard:",
    "web.settings.discord.status_embed_json_label": "Status-Embed-JSON",
    "web.settings.discord.status_config_json_label": "Status-Config-JSON",
    "web.settings.discord.embed_desc1": "Das Server-Status-Embed ist anpassbar, indem du das obige JSON bearbeitest.",
    "web.settings.discord.embed_desc2": "Hinweis:",
    "web.settings.discord.embed_desc3": " Verwende den Befehl ",
    "web.settings.discord.embed_desc4": " in einem Kanal, in dem der Bot die Berechtigung \"Nachricht senden\" hat, um das Embed einzurichten.",
    "web.settings.discord.discard_changes": "Änderungen verwerfen",
    "web.settings.discord.reset_default": "Auf Standard zurücksetzen",
    "web.settings.discord.val_token_required": "Du musst einen Discord-Bot-Token angeben, um den Bot zu aktivieren.",
    "web.settings.discord.val_guild_required": "Du musst eine Server-ID angeben, um den Bot zu aktivieren.",
    "web.settings.discord.val_jsons_required": "Du musst sowohl das Embed-JSON als auch das Config-JSON angeben, um den Bot zu aktivieren.",

    // web.settings.fxserver
    "web.settings.fxserver.data_folder_label": "Server-Datenordner",
    "web.settings.fxserver.data_folder_required": "Der Server-Datenordner ist erforderlich.",
    "web.settings.fxserver.data_folder_setup": "Wenn du zur Setup-Seite zurückkehren möchtest, klicke stattdessen auf die Schaltfläche \"Zurücksetzen\".",
    "web.settings.fxserver.cfg_path_required": "Der CFG-Dateipfad ist erforderlich.",
    "web.settings.fxserver.cfg_path_suggested": "Der Wert sollte wahrscheinlich `server.cfg` sein.",
    "web.settings.fxserver.onesync_err_title": "Du kannst OneSync nicht in den Startargumenten setzen.",
    "web.settings.fxserver.onesync_err_msg": "Bitte verwende die Auswahlbox darunter.",
    "web.settings.fxserver.reset_data_title": "Server-Datenpfad zurücksetzen",
    "web.settings.fxserver.reset_data_msg1": "Bist du sicher, dass du den Server-Datenpfad zurücksetzen möchtest?",
    "web.settings.fxserver.reset_data_msg2": "Dies löscht keine Ressourcen-Dateien oder Datenbank",
    "web.settings.fxserver.reset_data_msg3": ", sondern setzt nur die vibeSM-Konfiguration zurück, sodass du zur Setup-Seite zurückkehren kannst.",
    "web.settings.fxserver.reset_data_msg4": "Wenn du möchtest, kannst du den Pfad später wieder auf den aktuellen Wert setzen.",
    "web.settings.fxserver.reset_data_msg5": "Warnung:",
    "web.settings.fxserver.reset_data_msg6": " Notiere dir den aktuellen Pfad, bevor du fortfährst, damit du ihn bei Bedarf später wieder einstellen kannst. Aktueller Pfad:",
    "web.settings.fxserver.resetting_data": "Server-Datenpfad wird zurückgesetzt...",
    "web.settings.fxserver.data_folder_desc1": "Der vollständige Pfad des Ordners, der ",
    "web.settings.fxserver.data_folder_desc2": "enthält",
    "web.settings.fxserver.data_folder_desc3": " den ",
    "web.settings.fxserver.data_folder_desc4": "-Ordner, normalerweise ist es derselbe Ort, der deine ",
    "web.settings.fxserver.data_folder_desc5": "Das Zurücksetzen dieses Werts ermöglicht dir, zur Setup-Seite zurückzukehren, ohne Dateien zu löschen.",
    "web.settings.fxserver.data_folder_desc6": "Dieser Pfad sollte beginnen mit",
    "web.settings.fxserver.restart_schedule_label": "Neustart-Zeitplan",
    "web.settings.fxserver.no_schedule": "Kein Zeitplan festgelegt. Klicke auf die + Schaltfläche, um eine Zeit hinzuzufügen.",
    "web.settings.fxserver.presets": "Voreinstellungen: ",
    "web.settings.fxserver.per_day": "/Tag",
    "web.settings.fxserver.add_time_title": "Neustart-Zeit hinzufügen",
    "web.settings.fxserver.timezone_warn1": "Warnung:",
    "web.settings.fxserver.timezone_warn2": " Deine Server-Zeitzone ist auf ",
    "web.settings.fxserver.timezone_warn3": " eingestellt, aber deine Browser-Zeitzone ist ",
    "web.settings.fxserver.timezone_warn4": ". Stelle sicher, dass du die Zeit gemäß der Server-Zeitzone konfigurierst.",
    "web.settings.fxserver.restart_schedule_desc1": "Zu welchen Tageszeiten der Server neu gestartet werden soll.",
    "web.settings.fxserver.restart_schedule_desc2": "Hinweis:",
    "web.settings.fxserver.restart_schedule_desc3": " Stelle sicher, dass dein Zeitplan mit deiner Serverzeit übereinstimmt und nicht mit deiner lokalen Zeit.",
    "web.settings.fxserver.quiet_mode_label": "Stiller Modus",
    "web.settings.fxserver.quiet_mode_desc1": "FXServer-Ausgabe nicht im Terminal anzeigen.",
    "web.settings.fxserver.quiet_mode_desc2": "Du kannst weiterhin die Live-Konsole verwenden.",
    "web.settings.fxserver.quiet_mode_locked": "Diese Einstellung ist gesperrt und kann nicht geändert werden.",
    "web.settings.fxserver.multi_hosting_label": "Multi-Hosting",
    "web.settings.fxserver.multi_hosting_desc": "Aktiviert die Multi-Hosting-Dashboard-Seite, mit der du mehrere separate FXServer gleichzeitig starten und verwalten kannst.",
    "web.settings.fxserver.cfg_path_label": "CFG-Dateipfad",
    "web.settings.fxserver.cfg_path_desc1": "Der Pfad zu deiner Server-Konfigurationsdatei, wahrscheinlich benannt ",
    "web.settings.fxserver.cfg_path_desc2": "Dies kann entweder absolut sein oder relativ zum Server-Datenordner.",
    "web.settings.fxserver.startup_args_label": "Startargumente",
    "web.settings.fxserver.startup_args_desc1": "Zusätzliche Befehlszeilenargumente, die an die FXServer-Instanz übergeben werden, wie z. B. NodeJS-CLI-Flags.",
    "web.settings.fxserver.startup_args_desc2": "Warnung:",
    "web.settings.fxserver.startup_args_desc3": " Du solltest diese Option mit hoher Wahrscheinlichkeit nicht verwenden. Befehle und ConVars sollten in deine ",
    "web.settings.fxserver.startup_args_desc4": " platziert werden.",
    "web.settings.fxserver.onesync_label": "OneSync",
    "web.settings.fxserver.onesync_placeholder": "OneSync-Option auswählen",
    "web.settings.fxserver.onesync_on": "An (empfohlen)",
    "web.settings.fxserver.onesync_legacy": "Legacy",
    "web.settings.fxserver.onesync_off": "Aus",
    "web.settings.fxserver.onesync_desc1": "Die meisten Server sollten ",
    "web.settings.fxserver.onesync_desc2": "OneSync An",
    "web.settings.fxserver.onesync_desc3": " verwenden. Die anderen Optionen gelten als veraltet und sollten nur verwendet werden, wenn du weißt, was du tust. Für weitere Informationen lies bitte die ",
    "web.settings.fxserver.onesync_desc4": "Dokumentation",
    "web.settings.fxserver.autostart_label": "Autostart",
    "web.settings.fxserver.autostart_desc1": "Server automatisch starten, nachdem ",
    "web.settings.fxserver.autostart_desc2": " gestartet wurde.",
    "web.settings.fxserver.tolerance_label": "Ressourcen-Start-Toleranz",
    "web.settings.fxserver.tolerance_placeholder": "Auswählen...",
    "web.settings.fxserver.tolerance_opt1": "1,5 Minuten (Standard)",
    "web.settings.fxserver.tolerance_opt2": "3 Minuten",
    "web.settings.fxserver.tolerance_opt3": "5 Minuten",
    "web.settings.fxserver.tolerance_opt4": "10 Minuten",
    "web.settings.fxserver.tolerance_desc1": "Beim Serverstart, wie lange auf den Start einer einzelnen Ressource gewartet werden soll, bevor der Server neu gestartet wird.",
    "web.settings.fxserver.tolerance_desc2": "Hinweis:",
    "web.settings.fxserver.tolerance_desc3": " Wenn du ",
    "web.settings.fxserver.tolerance_desc4": "-Fehler bekommst, erhöhe diesen Wert.",

    // web.settings.gamemenu
    "web.settings.gamemenu.label": "Spielmenü",
    "web.settings.gamemenu.desc1": "Wenn aktiviert, können Admins das Menü öffnen, indem sie ",
    "web.settings.gamemenu.desc2": " eingeben oder die in den FiveM/RedM-Einstellungen konfigurierte Tastenkombination verwenden.",
    "web.settings.gamemenu.align_right_label": "Menü rechts ausrichten",
    "web.settings.gamemenu.align_right_desc": "Menü auf die rechte Bildschirmseite verschieben.",
    "web.settings.gamemenu.align_right_checked": "Rechts ausgerichtet",
    "web.settings.gamemenu.align_right_unchecked": "Links ausgerichtet",
    "web.settings.gamemenu.page_key_label": "Menü-Seitenwechsel-Taste",
    "web.settings.gamemenu.page_key_placeholder": "Hier klicken und die Taste zum Wechseln drücken",
    "web.settings.gamemenu.page_key_desc1": "Die Taste, die zum Wechseln der Tabs im Menü verwendet wird.",
    "web.settings.gamemenu.page_key_desc2": "Klicke oben und drücke eine beliebige Taste, um die Konfiguration zu ändern.",
    "web.settings.gamemenu.page_key_desc3": "Hinweis:",
    "web.settings.gamemenu.page_key_desc4": " Der Standard ist ",
    "web.settings.gamemenu.page_key_desc5": ", und du kannst nicht ",
    "web.settings.gamemenu.page_key_desc6": " oder ",
    "web.settings.gamemenu.effect_label": "Spielermodus-Wechsel-Effekt",
    "web.settings.gamemenu.effect_desc1": "Partikeleffekt und Sound abspielen, wenn ein Admin NoClip, God Mode usw. verwendet.",
    "web.settings.gamemenu.effect_desc2": "Warnung:",
    "web.settings.gamemenu.effect_desc3": " Diese Option hilft, Admin-Missbrauch während PvP zu verhindern, indem es für alle Spieler sichtbar/hörbar gemacht wird, dass ein Admin einen speziellen Modus verwendet. Wir empfehlen, es aktiviert zu lassen.",

    // web.settings.gamenotif
    "web.settings.gamenotif.hide_admin_punish_label": "Admin-Name bei Bestrafungen ausblenden",
    "web.settings.gamenotif.hide_admin_punish_desc1": "Den Spielern niemals den Admin-Namen bei ",
    "web.settings.gamenotif.hide_admin_punish_desc2": "Bans",
    "web.settings.gamenotif.hide_admin_punish_desc3": " oder ",
    "web.settings.gamenotif.hide_admin_punish_desc4": "Verwarnungen",
    "web.settings.gamenotif.hide_admin_punish_desc5": " anzeigen. Diese Information ist weiterhin im Verlauf und in den Logs verfügbar.",
    "web.settings.gamenotif.hide_admin_punish_checked": "Versteckt",
    "web.settings.gamenotif.hide_admin_punish_unchecked": "Sichtbar",
    "web.settings.gamenotif.hide_admin_msg_label": "Admin-Name bei Nachrichten ausblenden",
    "web.settings.gamenotif.hide_admin_msg_desc1": "Den Admin-Namen bei ",
    "web.settings.gamenotif.hide_admin_msg_desc2": "Ankündigungen",
    "web.settings.gamenotif.hide_admin_msg_desc3": " oder ",
    "web.settings.gamenotif.hide_admin_msg_desc4": "Direktnachrichten",
    "web.settings.gamenotif.hide_admin_msg_desc5": " nicht anzeigen. Diese Information ist weiterhin in der Live-Konsole und in den Logs verfügbar.",
    "web.settings.gamenotif.hide_announcement_label": "Ankündigungs-Benachrichtigungen ausblenden",
    "web.settings.gamenotif.hide_announcement_desc1": "Unterdrückt die Anzeige von Ankündigungen, sodass du deine eigene Ankündigung über das Event ",
    "web.settings.gamenotif.hide_announcement_desc2": "Dokumentation",
    "web.settings.gamenotif.hide_dm_label": "Direktnachrichten-Benachrichtigung ausblenden",
    "web.settings.gamenotif.hide_dm_desc1": "Unterdrückt die Anzeige von Direktnachrichten, sodass du deine eigene Direktnachrichten-Benachrichtigung über das Event ",
    "web.settings.gamenotif.hide_dm_desc2": "Dokumentation",
    "web.settings.gamenotif.hide_warn_label": "Verwarnungs-Benachrichtigung ausblenden",
    "web.settings.gamenotif.hide_warn_desc1": "Unterdrückt die Anzeige von Verwarnungen, sodass du deine eigene Verwarnung über das Event ",
    "web.settings.gamenotif.hide_warn_desc2": "Dokumentation",
    "web.settings.gamenotif.hide_restart_label": "Geplante Neustart-Warnungen ausblenden",
    "web.settings.gamenotif.hide_restart_desc1": "Unterdrückt die Anzeige von geplanten Neustart-Warnungen, sodass du deine eigene Warnung über das Event ",
    "web.settings.gamenotif.hide_restart_desc2": "Dokumentation",

    // web.settings.language (the sub-settings, not the top-level)
    "web.settings.language.hub_title": "Community-Sprachen-Hub",
    "web.settings.language.loading_community": "Community-Sprachen werden geladen...",
    "web.settings.language.no_packs": "Noch keine Community-Sprachpakete verfügbar. Sei der Erste, der eines teilt!",
    "web.settings.language.pack_contains": "Community-Lokalisierungspaket mit %{count} Phrasen-Überschreibungen.",
    "web.settings.language.import_apply": "Importieren und Anwenden",
    "web.settings.language.share_title": "Deine aktuellen benutzerdefinierten Übersetzungen teilen",
    "web.settings.language.share_pack_title": "Sprachpaket-Titel",
    "web.settings.language.share_pack_placeholder": "z. B. Deutsch Umgangssprachlich, Piraten-Dialekt",
    "web.settings.language.share_author": "Autorenname",
    "web.settings.language.share_author_placeholder": "Dein Name oder Teamname",
    "web.settings.language.share_btn": "Mit Community teilen",
    "web.settings.language.editor_placeholder": "Übersetzungstext eingeben...",
    "web.settings.language.search_placeholder": "Phrasen suchen...",
    "web.settings.language.all_categories": "Alle Kategorien",
    "web.settings.language.current_saved": "Aktuell gespeichertes Locale",
    "web.settings.language.base_template": "Basisvorlage",
    "web.settings.language.no_match": "Keine Übersetzungsschlüssel entsprechen deinen Suchkriterien.",
    "web.settings.language.desc_custom": "Legt die primäre Sprache für Chat, Konsolen-Log-Kategorien und Bot-Nachrichten fest. Wähle Benutzerdefiniert, um die unten geänderten Übersetzungen zu laden.",
    "web.settings.language.import_applied_success": "Community-Sprache \"%{name}\" erfolgreich angewendet!",
    "web.settings.language.import_toast": "Community-Sprache \"%{name}\" wird importiert und angewendet...",
    "web.settings.language.err_save_lang": "Aktive Systemsprache konnte nicht aktualisiert werden.",
    "web.settings.language.err_import_trans": "Übersetzungen konnten nicht in locale.json importiert werden.",
    "web.settings.language.err_apply_comm": "Fehler beim Anwenden der Community-Locale.",
    "web.settings.language.err_fill_share": "Bitte Sprachtitel und Autorennamen ausfüllen.",
    "web.settings.language.share_success": "Deine Übersetzungen wurden erfolgreich mit der Community geteilt!",
    "web.settings.language.err_share_pack": "Sprachpaket konnte nicht geteilt werden.",
    "web.settings.language.err_connect_comm": "Verbindung zur Community-Backend-Datenbank fehlgeschlagen.",
    "web.settings.language.err_load_keys": "Übersetzungsschlüssel konnten nicht geladen werden.",
    "web.settings.language.updating_system_lang": "Systemsprache wird aktualisiert...",
    "web.settings.language.system_lang_updated": "Primäre Systemsprache erfolgreich aktualisiert!",
    "web.settings.language.err_save_lang_setting": "Spracheinstellung konnte nicht gespeichert werden.",
    "web.settings.language.custom_locale_meta": "Benutzerdefiniertes Locale",
    "web.settings.language.err_save_trans": "Fehler beim Speichern der Übersetzungen.",
    "web.settings.language.err_save_trans_generic": "Beim Speichern der Übersetzungen ist ein Fehler aufgetreten.",
    "web.settings.language.saving_custom_trans": "Benutzerdefinierte Übersetzungen werden in locale.json gespeichert...",
    "web.settings.language.custom_trans_saved": "Benutzerdefinierte Übersetzungsdatei erfolgreich gespeichert!",
    "web.settings.language.alert_editor_desc": "Alle geänderten Felder werden kompiliert und dynamisch in die benutzerdefinierte locale.json-Datei deines Servers geschrieben. Stelle sicher, dass deine aktive Sprache oben auf Benutzerdefiniert eingestellt ist, um diese Vorlagen zu laden.",

    // web.settings.theme
    "web.settings.theme.library_title": "Community-Themes-Bibliothek",
    "web.settings.theme.loading_community": "Community-Themes-Datenbank wird geladen...",
    "web.settings.theme.no_themes": "Noch keine Community-Themes hochgeladen. Sei der Erste, der eines teilt!",
    "web.settings.theme.apply_theme_toast": "Community-Theme \"%{name}\" angewendet!",
    "web.settings.theme.err_select_share": "Bitte wähle ein Theme zum Teilen aus.",
    "web.settings.theme.err_enter_author": "Bitte gib deinen Namen als Autor ein.",
    "web.settings.theme.err_not_found": "Theme nicht gefunden.",
    "web.settings.theme.err_failed_share": "Theme konnte nicht geteilt werden.",
    "web.settings.theme.err_connect_comm": "Verbindung zur Community-Backend-Datenbank fehlgeschlagen.",
    "web.settings.theme.share_success": "Theme erfolgreich an die Community geteilt!",
    "web.settings.theme.copied_hex_toast": "HEX-Farbe %{hex} in die Zwischenablage kopiert!",
    "web.settings.theme.saved_toast": "Theme-Einstellungen gespeichert.",
    "web.settings.theme.dark_scheme": "Dunkles Farbschema",
    "web.settings.theme.light_scheme": "Helles Farbschema",
    "web.settings.theme.delete_theme_title": "Benutzerdefiniertes Theme löschen",
    "web.settings.theme.custom_suffix": " (Benutzerdefiniert)",
    "web.settings.theme.deleted_toast": "Theme \"%{name}\" gelöscht.",
    "web.settings.theme.by_author": "von %{author}",
    "web.settings.theme.canvas": "Leinwand",
    "web.settings.theme.accent": "Akzent",
    "web.settings.theme.applied": "Angewendet",
    "web.settings.theme.apply": "Anwenden",
    "web.settings.theme.hex_format": "HEX-Format",
    "web.settings.theme.copy_hex_color": "HEX-Farbe kopieren",
    "web.settings.theme.theme_id_label": "Theme-ID (Kleinbuchstaben, keine Leerzeichen)",
    "web.settings.theme.display_label": "Anzeige-Bezeichnung",
    "web.settings.theme.theme_json_copied_toast": "Theme-JSON in die Zwischenablage kopiert!",
    "web.settings.theme.err_valid_name": "Bitte gib einen gültigen, einzigartigen Theme-Namen ein.",
    "web.settings.theme.err_enter_label": "Bitte gib eine Theme-Bezeichnung ein.",
    "web.settings.theme.err_already_exists": "Ein Theme mit diesem Namen existiert bereits.",
    "web.settings.theme.theme_created_toast": "Theme \"%{label}\" wurde erfolgreich erstellt und angewendet!",
    "web.settings.theme.err_missing_fields": "Erforderliche Felder fehlen: 'name', 'isDark', 'style'.",
    "web.settings.theme.theme_imported_success": "Theme \"%{label}\" erfolgreich importiert!",
    "web.settings.theme.err_parse_json": "Fehler beim Parsen des Theme-JSON: %{error}",
    "web.settings.theme.active_theme_desc": "Wähle aus Standard-Themes, angepassten Voreinstellungs-Themes oder klicke, um benutzerdefinierte Themes zu laden, die in dieser Browsersitzung gespeichert sind.",
    "web.settings.theme.comm_themes_desc": "Durchsuche, lade herunter und wende Theme-Anpassungspakete an, die von anderen vibeSM-Community-Administratoren erstellt und geteilt wurden.",
    "web.settings.theme.share_theme_label": "Theme an Community teilen",
    "web.settings.theme.share_select_label": "Theme zum Teilen auswählen",
    "web.settings.theme.share_select_placeholder": "Eines deiner benutzerdefinierten Themes auswählen...",
    "web.settings.theme.share_author_label": "Autorenname",
    "web.settings.theme.share_author_placeholder": "Dein Name oder Servername",
    "web.settings.theme.share_btn": "Theme hochladen und teilen",
    "web.settings.theme.share_desc": "Veröffentliche deine angepassten Themes direkt im gemeinsamen Community-Katalog, damit andere Administratoren weltweit sie abrufen und genießen können.",
    "web.settings.theme.creator_dark_scheme_label": "Dunkles Farbschema-Styling verwenden (empfiehlt dunklen Text auf hellen Akzenten)",
    "web.settings.theme.creator_hsl_title": "Aktive Variablen-HSL-Konfiguration",
    "web.settings.theme.creator_accent_label": "Primärer Akzent",
    "web.settings.theme.creator_bg_label": "Kern-Hintergrund",
    "web.settings.theme.creator_card_label": "Karten-Hintergrund",
    "web.settings.theme.creator_fg_label": "Text/Vordergrund",
    "web.settings.theme.creator_card_fg_label": "Kartentext",
    "web.settings.theme.creator_border_label": "Feine Ränder",
    "web.settings.theme.creator_btn": "Theme erstellen und anwenden",
    "web.settings.theme.creator_desc": "Passe Farbvariablen-Parameter visuell in HSL, HSV oder HEX an, um ein hochwertiges benutzerdefiniertes dynamisches Theme zu erstellen. Umrisse, Schatten und sekundäre Konfigurationen werden automatisch mathematisch ausbalanciert.",
    "web.settings.theme.import_export_label": "Theme importieren und exportieren",
    "web.settings.theme.export_json_label": "Aktives Theme-JSON (Export)",
    "web.settings.theme.export_desc": "Klicke in das Feld, um das aktive Theme-JSON-Setup in die Zwischenablage zu kopieren und mit anderen vibeSM/txAdmin-Admins zu teilen.",
    "web.settings.theme.import_json_label": "Theme-JSON einfügen (Import)",
    "web.settings.theme.import_btn": "Theme importieren",

    // web.multi_hosting (remaining untranslated)
    "web.multi_hosting.port_info": "Stelle sicher, dass dieser Port in deiner Firewall (sowohl TCP als auch UDP) geöffnet ist, damit Spieler sich verbinden können.",
    "web.multi_hosting.create_server": "Neuen Server erstellen",
    "web.multi_hosting.create_and_deploy": "Neuen Server erstellen und bereitstellen",
    "web.multi_hosting.base_settings": "Grundeinstellungen",
    "web.multi_hosting.discord_bot": "Discord-Bot",
    "web.multi_hosting.bans": "Bans",
    "web.multi_hosting.whitelist": "Whitelist",
    "web.multi_hosting.base_dir_path": "Basis-Verzeichnispfad (wo der Server erstellt/bereitgestellt wird)",
    "web.multi_hosting.join_link": "Beitreten-Link:",
    "web.multi_hosting.loading_configs": "Konfigurationen werden geladen...",
    "web.multi_hosting.err_loading_configs": "Fehler beim Laden der Konfigurationen: %{error}",
    "web.multi_hosting.saving_server_config": "Serverkonfiguration wird gespeichert...",
    "web.multi_hosting.saving_settings": "%{card}-Einstellungen werden gespeichert...",
    "web.multi_hosting.err_saving_settings": "Fehler beim Speichern der %{card}-Einstellungen:",

    // web.auth_error
    "web.auth_error.invalid_session_title": "Ungültige Browser-Sitzung.",
    "web.auth_error.invalid_session_desc_1": "Möglicherweise hast du vibeSM kurz vor dem Betreten dieser Seite neu gestartet.",
    "web.auth_error.invalid_session_desc_2": "Bitte kehre zurück und versuche es erneut.",
    "web.auth_error.clock_desync_title": "Bitte aktualisiere/synchronisiere die Uhr deines VPS.",
    "web.auth_error.clock_desync_desc": "Anmeldung fehlgeschlagen, da die Uhrzeit dieses Hosts falsch ist. Bitte stelle sicher, dass sie mit dem Internet synchronisiert ist.",
    "web.auth_error.timeout_title": "Verbindung zu FiveM-Servern hat das Zeitlimit überschritten.",
    "web.auth_error.timeout_desc": "Bitte versuche es erneut oder melde dich mit deinem bestehenden Benutzernamen und Backup-Passwort an.",
    "web.auth_error.login_aborted_title": "Anmeldung abgebrochen",
    "web.auth_error.login_aborted_desc_1": "Der Cfx.re-Anmeldevorgang wurde abgebrochen.",
    "web.auth_error.login_aborted_desc_2": "Kehre zur Anmeldeseite zurück, um es erneut zu versuchen.",
    "web.auth_error.login_logout_desc_1": "Der Cfx.re-Anmeldevorgang wurde abgebrochen, da du dich vom Cfx.re-Konto abgemeldet hast.",
    "web.auth_error.login_logout_desc_2": "Kehre zur Anmeldeseite zurück, um es erneut zu versuchen.",
    "web.auth_error.master_set_title": "Master-Konto bereits eingerichtet",
    "web.auth_error.master_set_desc": "Bitte gehe zurück zur Anmeldeseite, um fortzufahren.",
    "web.auth_error.not_admin_title": "Das Cfx.re-Konto '%{name}' ist kein Admin.",
    "web.auth_error.not_admin_desc_1": "Das obige Konto mit dem Identifier ",
    "web.auth_error.not_admin_desc_2": " ist keinem in vibeSM registrierten Konto zugeordnet.",
    "web.auth_error.not_admin_desc_3": "Du kannst auch versuchen, dich mit deinem Benutzernamen und Backup-Passwort anzumelden.",
    "web.auth_error.unknown_error_title": "Unbekannter Fehler:",
    "web.auth_error.try_again": "Erneut versuchen",
    "web.auth_error.network_error": "Netzwerkfehler",
    "web.auth_error.restart_desc": "Wenn du vibeSM geschlossen hast, starte es bitte neu und versuche es erneut.",
    "web.auth_error.unknown_error": "Unbekannter Fehler",

    // web.auth
    "web.auth.pin.autofilled": "Automatisch ausgefüllt",
    "web.auth.pin.no_cfx_linked": "Kein Cfx.re-Konto verknüpft",
    "web.auth.pin.instructions": "Gib die PIN aus dem Terminal ein.",
    "web.auth.pin.link_btn": "Konto verknüpfen",
    "web.auth.register.err_discord_id": "Die Discord-ID muss die numerische \"Benutzer-ID\" sein, nicht der Benutzername.\\n Du kannst das Feld auch leer lassen.",
    "web.auth.register.err_agree_terms": "Du MUSST den Nutzungsbedingungen zustimmen.",
    "web.auth.register.err_password_length": "Das Passwort muss zwischen %{min} und %{max} Zeichen lang sein.",
    "web.auth.register.err_passwords_dont_match": "Die Passwörter stimmen nicht überein.",
    "web.auth.register.cfx_account": "Cfx.re-Konto",
    "web.auth.register.discord_id": "Discord-ID",
    "web.auth.register.optional": "(optional)",
    "web.auth.register.backup_password": "Backup-Passwort",
    "web.auth.register.confirm_password": "Passwort bestätigen",
    "web.auth.register.terms_prefix": "Ich habe die ",
    "web.auth.register.creator_pla": "Creator-PLA",
    "web.auth.register.terms_and": " sowie die ",
    "web.auth.register.license_link": "vibeSM-Lizenz",
    "web.auth.register.register_btn": "Registrieren",
    "web.auth.register.authenticating": "Authentifizierung...",
    "web.auth.login.logging_in": "Anmeldung...",

    // web.notfound
    "web.notfound.title": "Nicht gefunden",
    "web.notfound.header": "404 | Nicht gefunden",
    "web.notfound.desc": "Die Seite %{path} scheint nicht korrekt zu sein.",
    "web.notfound.return": "Zurück zum Dashboard?",

    // web.unauthorized
    "web.unauthorized.permission": "Berechtigung",
    "web.unauthorized.master_required": "Du musst das Master-Konto sein, um die Seite %{page} anzuzeigen.",
    "web.unauthorized.perms_required_prefix": "Du hast nicht die erforderliche ",
    "web.unauthorized.perms_required_suffix": ", um die Seite %{page} anzuzeigen.",
    "web.unauthorized.contact_owner": "Bitte kontaktiere deinen Serverbesitzer, wenn du glaubst, dass dies ein Fehler ist.",
    "web.unauthorized.access_denied": "Zugriff verweigert",
    "web.unauthorized.return": "Zurück zum Dashboard",

    // web.ban
    "web.ban.err_reason_length": "Der Grund muss mindestens 3 Zeichen lang sein.",
    "web.ban.err_no_identifiers": "Du musst mindestens einen Identifier eingeben.",
    "web.ban.err_invalid_identifiers": "Du musst mindestens einen gültigen Identifier eingeben.",
    "web.ban.banning_toast": "Identifier werden gebannt...",
    "web.ban.banned_toast": "Identifier gebannt.",
    "web.ban.title": "Identifier bannen",
    "web.ban.desc_main_1": "Hier kannst du bestimmte Spieler-Identifier (wie ",
    "web.ban.desc_main_2": " und ",
    "web.ban.desc_main_3": ") bannen, ohne nach einem registrierten Spieler suchen zu müssen.",
    "web.ban.desc_legacy_1": "Bans ohne einen einzelnen ",
    "web.ban.desc_legacy_2": "-Identifier gelten als ",
    "web.ban.desc_legacy_3": " und sollten nach Möglichkeit vermieden werden.",
    "web.ban.err_permission_1": "Du benötigst die ",
    "web.ban.err_permission_2": "-Berechtigung, um diese Funktion zu nutzen.",
    "web.ban.identifiers_label": "Identifier",
    "web.ban.identifiers_placeholder": "discord:xxxx, fivem:xxxx, license:xxxx, steam:xxxx, etc...",
    "web.ban.clear_btn": "Löschen",
    "web.ban.banning_btn": "Banne...",
    "web.ban.apply_btn": "Ban anwenden",

    // web.system_log
    "web.system_log.end_of_log": "[ENDE DES LOGS - SEITE AKTUALISIEREN, UM MEHR ZU LADEN]",
    "web.system_log.console_title": "Konsolenprotokoll",
    "web.system_log.console_desc": "Ausgabe von vibeSM an sein übergeordnetes Terminal, einschließlich normalerweise versteckter Debug-Nachrichten.",
    "web.system_log.action_title": "Aktionsprotokoll",
    "web.system_log.action_desc": "Protokoll aller von vibeSM oder einem Admin durchgeführten Aktionen.",
    "web.system_log.loading": "Laden...",
    "web.system_log.err_fetching": "Fehler beim Abrufen von %{title}:",

    // web.dashboard
    "web.dashboard.err_unknown_state": "Unbekannter Konfigurationsstatus: %{state}",
    "web.dashboard.stats.uptime": "Betriebszeit",
    "web.dashboard.stats.median": "Median",
    "web.dashboard.stats.fxserver": "FXServer",
    "web.dashboard.stats.nodejs": "Node.js",
    "web.dashboard.stats.title": "Server-Statistiken",
    "web.dashboard.stats.minutes_ago": "(vor Minuten)",
    "web.dashboard.stats.live": "(live)",
    "web.dashboard.player_drop.total": "Gesamt:",
    "web.dashboard.player_drop.no_disconnects": "In den letzten 6 Stunden haben sich keine Spieler vom Server getrennt.",
    "web.dashboard.player_drop.title": "Spieler-Disconnect-Ursache (letzte 6h)",
    "web.dashboard.perf.tick_duration": "Tick-Dauer:",
    "web.dashboard.perf.time_spent": "Aufgewendete Zeit:",
    "web.dashboard.perf.tick_count": "Tick-Anzahl:",
    "web.dashboard.perf.percent_total": "Prozent der Gesamtzeit",
    "web.dashboard.perf.good": "gut",
    "web.dashboard.perf.bad": "schlecht",
    "web.dashboard.perf.last_minute": "(letzte Minute)",
    "web.dashboard.perf.no_data": "Daten sind noch nicht verfügbar. Das Thread-Performance-Diagramm erscheint kurz nachdem der Server online ist.",
    "web.dashboard.perf.title": "%{thread}-Performance",
    "web.dashboard.perf.filter_placeholder": "Nach Admin filtern",
    "web.dashboard.full_perf.render_error": "Rendering-Fehler: %{error}",
    "web.dashboard.full_perf.retry": "Wiederholen",
    "web.dashboard.full_perf.err_bad_request": "Laden der Diagrammdaten fehlgeschlagen: ungültige Anfrage.",
    "web.dashboard.full_perf.err_invalid_thread": "Laden der Diagrammdaten fehlgeschlagen: ungültiger Thread-Name.",
    "web.dashboard.full_perf.err_data_unavailable": "Laden der Diagrammdaten fehlgeschlagen: Daten sind noch nicht verfügbar.",
    "web.dashboard.full_perf.not_enough_data_1": "Es sind noch nicht genügend Daten vorhanden, um das Diagramm anzuzeigen.",
    "web.dashboard.full_perf.not_enough_data_2": "Das Diagramm benötigt mindestens 30 Minuten Server-Laufzeitdaten.",
    "web.dashboard.full_perf.title": "Server-Performance",

    // web.2fa
    "web.2fa.title": "Zwei-Faktor-Authentifizierung",
    "web.2fa.setup_required": "Zwei-Faktor-Authentifizierung wird von den globalen Einstellungen vorgeschrieben.",
    "web.2fa.enter_code": "Bitte gib deinen 6-stelligen Bestätigungscode ein.",
    "web.2fa.placeholder": "6-stelliger Bestätigungscode",
    "web.2fa.cancel": "Abbrechen",
    "web.2fa.verify_enable": "Überprüfen und aktivieren",
    "web.2fa.verify_code": "Code überprüfen",
    "web.2fa.back": "Zurück",
    "web.2fa.active": "Aktiv",
    "web.2fa.enabled_msg": "Zwei-Faktor-Authentifizierung ist aktiviert.",
    "web.2fa.secured_msg": "Dein Konto ist mit einer Authenticator-App gesichert. Du wirst aufgefordert, einen Bestätigungscode einzugeben, wenn du dich mit deinem Passwort anmeldest.",
    "web.2fa.verification_code": "Bestätigungscode",
    "web.2fa.disable_placeholder": "6-stelligen Code zum Deaktivieren eingeben",
    "web.2fa.disabling": "Wird deaktiviert...",
    "web.2fa.disable_btn": "2FA deaktivieren",
    "web.2fa.intro_msg": "Zwei-Faktor-Authentifizierung fügt deinem Konto eine zusätzliche Sicherheitsebene hinzu, indem ein Bestätigungscode von einer Authenticator-App (z. B. Google Authenticator, Authy, Microsoft Authenticator) bei der Anmeldung verlangt wird.",
    "web.2fa.generating": "Setup wird generiert...",
    "web.2fa.setup_btn": "Authenticator einrichten",
    "web.2fa.scan_msg": "Scanne den QR-Code mit deiner Authenticator-App oder gib den manuellen Schlüssel unten ein. Gib dann den 6-stelligen Code aus der App ein, um die Einrichtung abzuschließen.",
    "web.2fa.key": "Schlüssel: %{key}",
    "web.2fa.verifying": "Wird überprüft...",
    "web.2fa.settings_title": "Zwei-Faktor-Authentifizierungs-Anforderung",
    "web.2fa.settings_switch": "Zwei-Faktor-Authentifizierung (2FA) für den Zugang zum Web-Panel vorschreiben",
    "web.2fa.settings_desc": "Wenn aktiviert, werden alle Administratoren, die die Passwort-Anmeldung verwenden, gezwungen, einen QR-Code zu scannen und 2FA zu konfigurieren, bevor sie auf das Web-Panel zugreifen können.",
    "web.2fa.settings_only_master": " Nur ein Master-Konto kann diese Einstellung ändern.",

    // web.history
    "web.history.title_total_warns": "Verwarnungen gesamt",
    "web.history.title_new_warns_7d": "Neue Verwarnungen letzte 7T",
    "web.history.title_total_bans": "Bans gesamt",
    "web.history.title_new_bans_7d": "Neue Bans letzte 7T",
    "web.history.search_type": "Suchtyp",
    "web.history.search_by": "Suchen nach %{type}",
    "web.history.filter_any_type": "Beliebiger Typ",
    "web.history.filter_bans": "Bans",
    "web.history.filter_warns": "Verwarnungen",
    "web.history.filter_any_admin": "Von beliebigem Admin",
    "web.history.filter_admin_placeholder": "Nach Admin filtern",
    "web.history.more": "Mehr",
    "web.history.bulk_remove": "Massenentfernung",
    "web.history.ban_templates": "Bannvorlagen",
    "web.history.row_unknown": "unbekannt",
    "web.history.err_req_failed": "Anfrage fehlgeschlagen.",
    "web.history.err_req_failed_with": "Anfrage fehlgeschlagen: %{error}",
    "web.history.err_fetch_failed": "Fehler beim Abrufen weiterer Daten: %{error}",
    "web.history.last_row_error": "Fehler: %{error}",
    "web.history.last_row_try_again": "Erneut versuchen?",
    "web.history.reached_end": "Du hast das Ende der Liste erreicht.",
    "web.history.no_actions": "Keine Aktionen gefunden.",
    "web.history.bug_report_1": "Du hast das Ende des Regenbogens gefunden, aber es gibt hier keinen Topf voll Gold.",
    "web.history.bug_report_2": "(das ist ein Bug, bitte melde ihn in %{discord})",
    "web.history.bug_report_2_prefix": "(das ist ein Bug, bitte melde ihn in ",
    "web.history.bug_report_2_suffix": ")",
    "web.history.header_action": "Aktion",
    "web.history.header_player": "Spieler",
    "web.history.header_reason": "Grund",
    "web.history.header_author": "Autor",
    "web.history.header_date_time": "Datum/Uhrzeit",
    "web.history.search_type_action_id": "Aktions-ID",
    "web.history.search_type_action_id_desc": "Aktionen nach ihrer ID suchen.",
    "web.history.search_type_reason": "Grund",
    "web.history.search_type_reason_placeholder": "Teil des Grunds eingeben, um danach zu suchen",
    "web.history.search_type_reason_desc": "Aktionen nach ihrem Grundinhalt suchen.",
    "web.history.search_type_player_ids": "Spieler-IDs",
    "web.history.search_type_player_ids_placeholder": "License, Discord, Steam, etc.",
    "web.history.search_type_player_ids_desc": "Aktionen nach Spieler-IDs suchen, durch Komma getrennt.",

    // web.liveconsole
    "web.liveconsole.title": "Live-Konsole",
    "web.liveconsole.search.no_results": "Keine Ergebnisse",
    "web.liveconsole.search.placeholder": "Suchbegriff",
    "web.liveconsole.search.case_sensitive": "Groß-/Kleinschreibung",
    "web.liveconsole.search.whole_word": "Ganzes Wort",
    "web.liveconsole.search.regex": "Regex",
    "web.liveconsole.search.previous": "Vorheriges",
    "web.liveconsole.search.next": "Nächstes",
    "web.liveconsole.search.close": "Schließen",
    "web.liveconsole.footer.err_no_perm": "Du hast keine Berechtigung, in die Konsole zu schreiben.",
    "web.liveconsole.footer.err_not_running": "Der Server läuft nicht.",
    "web.liveconsole.footer.err_lost_connection": "Socket-Verbindung verloren.",
    "web.liveconsole.footer.placeholder": "Befehl eingeben...",
    "web.liveconsole.footer.saved": "Gespeichert",
    "web.liveconsole.footer.search": "Suchen",
    "web.liveconsole.footer.clear": "Löschen",
    "web.liveconsole.footer.download": "Herunterladen",
    "web.liveconsole.bookmark.close": "Schließen",
    "web.liveconsole.bookmark.save": "Speichern",
    "web.liveconsole.bookmark.remove": "Entfernen",
    "web.liveconsole.bookmark.history_cleared": "Verlauf gelöscht",
    "web.liveconsole.bookmark.save_command": "Befehl speichern",
    "web.liveconsole.bookmark.prompt_msg": "Gib den zu speichernden Befehl ein:",
    "web.liveconsole.bookmark.history_title": "Verlauf",
    "web.liveconsole.bookmark.clear_history": "Verlauf löschen",
    "web.liveconsole.bookmark.history_empty": "Der Befehlsverlauf ist leer.",
    "web.liveconsole.bookmark.saved_title": "Gespeichert",
    "web.liveconsole.bookmark.add_new": "Neu hinzufügen",
    "web.liveconsole.bookmark.saved_empty_1": "Keine gespeicherten Befehle vorhanden.",
    "web.liveconsole.bookmark.saved_empty_2": "Um einen Befehl zu speichern, klicke auf das Stern-Symbol daneben.",
    "web.liveconsole.err_copy_failed_sad": "Kopieren in die Zwischenablage fehlgeschlagen :(",
    "web.liveconsole.err_copy_failed": "Kopieren in die Zwischenablage fehlgeschlagen:",
    "web.liveconsole.console_cleared": "[Konsole gelöscht]",
    "web.liveconsole.connecting": "Verbindung wird hergestellt...",

    // web.players (remaining untranslated ones)
    "web.players.title_played_24h": "Spieler letzte 24h",
    "web.players.filters_title": "Suchfilter",
};

// Apply translations
let count = 0;
for (const [dotPath, value] of Object.entries(translations)) {
    setNestedValue(deJson, dotPath, value);
    count++;
}

fs.writeFileSync(deJsonPath, JSON.stringify(deJson, null, 4) + '\n', 'utf-8');
console.log(`Applied ${count} German translations to de.json`);
